(define post-04-le-veteran-fr
  (lambda ()
    (list-of
      "04-le-veteran"
      "Le Vétéran Épuisé"
      (list-of
        "Marcus développait des logiciels depuis vingt-trois ans. Il avait survécu à quatre réorganisations, deux acquisitions, une migration de l'hébergement local vers le cloud qui avait pris trois ans sans amélioration perceptible, et un incident de systèmes distribués qui le réveillait encore la nuit. Il était venu à la Cale parce que, selon ses propres mots, il essayait une dernière chose avant d'arrêter d'essayer des choses."
        "Il passa sa première semaine à lire les documents de conception du dépôt sans y faire de commentaires. Cela rendait les ingénieurs juniors nerveux. Au huitième jour, lors d'une session de revue, il dit : « Je veux savoir ce qui n'est pas là-dedans. » Le silence s'installa dans la pièce. Il précisa : « Chaque système que j'ai vu comporte quelque chose d'absent en son centre que tout le monde prétend ne pas voir. Je veux savoir ce que celui-ci prétend ignorer. »"
        "Ce qui manquait dans le dépôt tel qu'il était conçu, c'était un moyen d'exprimer qu'une chose avait été délibérément laissée de côté. On pouvait ajouter. On pouvait dériver. On pouvait rétracter par dérivation. Mais il n'existait pas de primitive pour « ceci est hors périmètre par conception ». Marcus passa une semaine à soutenir que c'était une fonctionnalité, pas un manque. Il perdit le débat, mais la discussion produisit le système d'attestation — un moyen d'enregistrer qu'un relecteur avait examiné un combinateur et choisi de ne pas l'étendre, pour des raisons désormais consignées dans le journal de travail."
        "Il fut la première personne à marquer un combinateur comme relu et à y ajouter une note indiquant : « Je n'aime pas cela, mais c'est le bon compromis. » La note n'était pas dans le hachage. Le hachage, c'était la logique. La note était dans le journal de travail, horodatée, attribuée à sa clé d'auteur. Vingt ans plus tard, un membre d'équipage sur un navire qu'il ne monterait jamais lirait cette note et comprendrait pourquoi une décision de conception qui semblait erronée au premier regard était en réalité correcte."
        "Marcus resta deux rotations. Il dit que la Cale était le premier environnement dans lequel il avait travaillé où l'absence d'une fonctionnalité était une position documentée plutôt qu'une hypothèse non documentée. Il le voulait comme un compliment. C'en était un."))))
