(define post-05-la-gamine-fr
  (lambda ()
    (list-of
      "05-la-gamine"
      "La Gamine de Tizi Ouzou"
      (list-of
        "Lylia avait dix-neuf ans quand elle intégra la cohorte d'apprentis de la Cale, la plus jeune du programme de quatre ans. Elle venait d'un collectif de makers à Tizi Ouzou où elle construisait des robots à partir de capteurs agricoles réutilisés depuis l'âge de quatorze ans. Elle n'avait jamais écrit de combinateur formel. Elle avait écrit beaucoup de logique qui s'avérait, sous la normalisation de Bruijn, identique à des combinateurs déjà existants."
        "L'instructeur qui travaillait avec elle — le Dr. Chen, qui préférait qu'on l'appelle simplement Chen — lui montra la primitive gamma dès son deuxième jour. Il l'écrivit au tableau : un combinateur catamorphique à correspondance de motifs qui s'auto-récursive sur les sous-expressions. Lylia le fixa longtemps puis dit : « Donc c'est une forme qui s'appelle elle-même sur ses propres morceaux. » Chen dit que c'était une façon de le formuler. Elle dit que ça ressemblait à la manière dont sa grand-mère décrivait le tissage : ce n'est pas toi qui fais bouger la navette, c'est le motif qui fait bouger la navette."
        "Elle écrivit son premier gamma correctement du premier coup. Puis elle en écrivit un deuxième qui était structurellement identique à un combinateur existant après normalisation. Le dépôt refusa de créer une nouvelle entrée et lui proposa à la place l'entrée existante. Elle fut brièvement vexée. Puis Chen lui montra que le combinateur existant avait été écrit par quelqu'un à Oslo dix-huit mois plus tôt, et que sa dérivation indépendante était enregistrée dans la lignée comme une découverte parallèle."
        "Ce fut le moment où elle comprit à quoi servait le dépôt. Non pas à empêcher les gens de penser la même chose. Mais à enregistrer qu'ils l'avaient fait. À dire : deux personnes ont atteint la même forme par des chemins différents. La forme est vraie."
        "Elle alla jusqu'à écrire la correspondance de surface en tamazight pour la bibliothèque de base, en travaillant à partir du cadre multilingue d'Amara et de son propre sens de ce que devaient sonner les termes techniques dans la langue dans laquelle elle avait grandi. Le dépôt accepta chaque combinateur. Les hachages correspondaient. Les noms étaient nouveaux et ils lui appartenaient."))))
