(define post-08-le-penseur-fr
  (lambda ()
    (list-of
      "08-le-penseur"
      "Le Penseur Civilisationnel"
      (list-of
        "Le Dr. Osei n'écrivait pas de code. Il était à la Cale parce que quelqu'un au comité de planification de la mission avait lu son livre — une oeuvre dense, admirée, rarement terminée, sur ce que les systèmes logiciels révèlent des civilisations qui les produisent — et avait décidé qu'avoir un historien des techniques dans l'équipe valait la place de couchette. La plupart des ingénieurs étaient sceptiques face à ce raisonnement. Ils le devinrent moins au fil du temps."
        "Sa contribution fut un mémo. Il était intitulé « De la distinction entre mémoire et archive » et faisait huit pages. L'argument central était le suivant : la plupart des archives numériques fonctionnaient comme une mémoire — elles stockaient ce qui s'était passé dans un format optimisé pour la récupération par des personnes qui savaient déjà ce qu'elles cherchaient. Le dépôt, argumentait-il, fonctionnait comme une archive — il stockait ce qui s'était passé dans un format qui préservait le raisonnement, pas seulement le résultat, et qui pouvait être interrogé par des personnes qui n'avaient pas été présentes lors du travail."
        "La distinction importait pour la mission. Si l'équipage avait besoin de déboguer un sous-système de survie cinq ans après le départ, il ne pourrait pas interroger les ingénieurs qui l'avaient construit. Les ingénieurs seraient sur Terre, inaccessibles, peut-être à la retraite, peut-être disparus. Ce qu'ils auraient, c'est le dépôt. Le dépôt leur montrerait non seulement ce que le sous-système faisait, mais la chaîne de dérivation qui l'avait produit, les vérifications écrites contre lui, les journaux de travail expliquant pourquoi certaines décisions avaient été prises."
        "Le mémo d'Osei fut largement lu et largement contesté. Les ingénieurs trouvaient son style d'écriture difficile. Il trouvait leur tendance à traiter toutes les questions conceptuelles comme des problèmes d'ingénierie attendrissante. Le mémo fut ajouté au dépôt comme document en langage naturel. Son hachage apparut dans la lignée de la spécification de conception de la suite de vérifications. Fatou l'y avait ajouté, sans l'annoncer, comme reconnaissance."
        "Il quitta la Cale après six semaines. Lors de la cérémonie de départ — modeste, tenue dans la baie de maintenance parce que la salle commune était en réparation — il dit qu'il était optimiste concernant la mission pour une seule raison : les gens sur le navire sauraient ce qu'ils ne savaient pas, parce que le dépôt le leur dirait. Il pensait que c'était plus rare que ça n'en avait l'air. Il avait raison."))))
