(define post-09-le-cycle-air-fr
  (lambda ()
    (list-of
      "09-le-cycle-air"
      "Le Cycle d'Air"
      (list-of
        "Le bogue se trouvait dans la routine d'équilibre de l'azote. Il y était depuis onze mois, dormant, attendant une combinaison spécifique de lectures de capteurs atmosphériques qui ne survenait que lorsque le cycle de purge mensuelle du système de recyclage se déroulait en même temps que le test de ventilation de la serre. Quand ces deux événements coïncidaient, la routine d'équilibre de l'azote produisait une valeur deux ordres de grandeur en-dessous du chiffre correct. La routine déclenchait alors une fausse alerte atmosphérique."
        "Personne ne trouva le bogue en lisant le code. Le code avait été relu deux fois et semblait correct aux deux relecteurs. La formule d'équilibre de l'azote était juste. La conversion des unités était juste. Le cas limite — l'interaction spécifique entre les deux cycles concurrents — n'était pas une condition que quiconque avait pensé à vérifier, car cela aurait nécessité de savoir que les deux cycles existaient et qu'ils pouvaient coïncider."
        "La suite de vérifications le trouva. Fatou avait ajouté une vérification pour la routine d'équilibre de l'azote qui exécutait un ensemble tabulé d'entrées contre des sorties attendues. La table incluait plusieurs valeurs du scénario de purge profonde, non pas parce que quelqu'un avait prédit le bogue, mais parce que Fatou avait demandé à l'équipe des systèmes environnementaux de lui donner une liste de combinaisons d'entrées « inhabituelles mais valides », et qu'ils l'avaient incluse sans savoir pourquoi elle en avait besoin."
        "Quand la vérification échoua lors d'une exécution de routine de la suite, elle produisit une discordance de hachage sur la valeur de sortie. Fatou en informa l'équipe des systèmes environnementaux. L'équipe trouva le bogue en quarante minutes. La correction tenait en trois lignes. La routine corrigée fut validée comme un nouveau hachage, avec un lien de lignée vers l'original et une entrée de journal de travail décrivant en détail le chemin de la découverte."
        "L'entrée se terminait ainsi : « Trouvé par une vérification, pas par une relecture. La vérification a été écrite avant que nous sachions ce qu'elle vérifiait. C'est à ça que servent les vérifications. » Cette phrase fut plus tard citée dans le deuxième mémo du Dr. Osei, qu'il écrivit depuis la Terre après avoir reçu une copie du journal de travail. Il l'appela un exemple de structure de connaissance produisant une récupération de connaissance. L'équipage appela ça de la chance, ce qui était aussi exact."))))
