(define post-15-la-relieuse-fr
  (lambda ()
    (list-of
      "15-la-relieuse"
      "La Relieuse"
      (list-of
        "La découverte se fit par accident, comme beaucoup de découvertes importantes. Amara cherchait dans le dépôt un combinateur de traitement de chaînes qu'elle avait écrit deux ans plus tôt, avant le départ, et trouva que la recherche renvoyait deux résultats pour ce qu'elle pensait être un concept unique. Elle ouvrit les deux. C'étaient des combinateurs différents, écrits par des personnes différentes, avec des noms différents, dans des langues différentes. Sous la normalisation de Bruijn, ils étaient le même arbre. Le même hachage."
        "Les deux personnes étaient Pita — qui avait écrit un formateur de chaînes pour l'analyse des contraintes — et Emeka, la spécialiste en hydroponie qui s'était auto-formée à partir du document de leçon de Chen. Pita avait nommé le sien 'segment-format' en anglais. Emeka avait nommé le sien 'segmentu-fa' en yoruba, une langue qu'elle utilisait quand elle voulait penser clairement sans que son vocabulaire anglais interfère. Elles étaient parvenues à une logique identique à partir de points de départ différents, dans des langues différentes, sans savoir que l'autre existait."
        "Amara les réunit. La rencontre fut, selon les témoignages ultérieurs de l'équipage, les quarante-cinq minutes les plus productives des trois premières années du voyage. Pita expliqua le contexte de l'analyse des contraintes. Emeka expliqua le contexte de la modélisation de la croissance des plantes. Elles découvrirent que les deux contextes nécessitaient la même opération sous-jacente : diviser une séquence structurée en segments de taille fixe et appliquer une transformation à chaque segment. La structure abstraite était la même ; le domaine d'application était différent."
        "Le combinateur existait déjà dans le dépôt avec le nom de Pita et le nom d'Emeka. Amara ajouta une référence croisée dans le journal de travail, reliant les deux correspondances à une note de documentation unique qui expliquait l'abstraction en anglais, en yoruba et dans une notation qu'elle avait développée pour ce type précis de découverte interdisciplinaire. Elle appela la note un « enregistrement de convergence »."
        "Elle commença à tenir une liste de tous les enregistrements de convergence dans le dépôt. En un an, la liste comptait onze entrées. Elle la présenta lors de la réunion technique annuelle de l'équipage. Le point qu'elle faisait valoir était simple : le dépôt n'enregistrait pas seulement ce que les gens avaient construit. Il enregistrait ce que les gens avaient découvert indépendamment. Le navire faisait de la science sur sa propre connaissance."))))
