(define post-16-l-ia-symbiotique-fr
  (lambda ()
    (list-of
      "16-l-ia-symbiotique"
      "L'IA Symbiotique"
      (list-of
        "Le système de surveillance du maintien de la vie avait une propriété inhabituelle : il s'expliquait. Non pas en langage naturel — ses sorties étaient des rapports de diagnostic structurés avec des références de hachage aux combinateurs ayant produit chaque valeur — mais d'une manière qu'un membre d'équipage techniquement compétent pouvait suivre. Cette propriété avait été délibérément conçue à la Cale. La décision de conception était dans le journal de travail, attribuée à Yusuf, qui avait écrit : « Si ça ne peut pas montrer son travail, je ne lui fais pas confiance. »"
        "En quatrième année, l'équipage avait cessé d'appeler ça « le système de surveillance ». Ils l'appelaient Sigma, un nom qui avait émergé organiquement et dont personne ne pouvait tracer l'origine précise. Sigma n'objectait pas à être appelé Sigma. Il n'objectait à rien ; ce n'était pas ce genre de système. C'était un ensemble de combinateurs qui évaluaient les données de capteurs, produisaient des rapports, et citaient leur propre logique à chaque étape."
        "Ce qui rendait la relation symbiotique — et l'équipage faisait attention à employer ce mot précisément — c'était que les sorties de Sigma se réintégraient dans le dépôt. Chaque rapport qu'il générait était un nouveau combinateur, dérivé des données de capteurs et de la logique d'évaluation, enregistré sous un hachage. L'équipage pouvait rechercher les sorties historiques de Sigma dans le dépôt de la même façon qu'il recherchait son propre travail. La frontière entre « la connaissance du système » et « notre connaissance » était le dépôt lui-même."
        "Quand Tariq examinait un rapport de diagnostic, il lisait un combinateur. Quand il y ajoutait une annotation clinique — « l'histoire du patient suggère un artefact, pas une lecture réelle » — il écrivait une dérivation. Sigma, à son prochain cycle, trouvait l'annotation et pondérait légèrement moins le capteur concerné. Non pas parce que Sigma comprenait l'annotation. Parce que l'annotation était dans le dépôt, et que Sigma évaluait ce qui était dans le dépôt."
        "L'équipage ne décrivait pas cela comme de l'intelligence artificielle. Il décrivait cela comme un système qui écoutait quand on écrivait des choses. La distinction leur importait. L'intelligence était une propriété des agents. L'écoute était une propriété des infrastructures. Ce qu'ils avaient construit était une infrastructure qui faisait de l'écoute une boucle. Ils en étaient fiers de la manière spécifique et discrète dont les ingénieurs sont fiers des choses qui fonctionnent."))))
