(define post-17-l-arriere-ancre-fr
  (lambda ()
    (list-of
      "17-l-arriere-ancre"
      "L'Arriéré des Ancres"
      (list-of
        "L'ancrage par horodatage ouvert fonctionnait en soumettant un hachage à un registre public maintenu sur Terre et en recevant une preuve que le hachage existait à un moment précis. La preuve était cryptographique : quiconque possédait le registre pouvait vérifier que le hachage avait été soumis avant un certain bloc, et donc que le contenu adressé par le hachage avait existé avant ce bloc."
        "Pendant les deux premières années du voyage, l'équipage soumettait des hachages au registre terrestre et recevait des preuves dans l'heure. Le délai de propagation aller-retour était suffisamment faible pour que le processus soit presque invisible. En troisième année, le délai était de quarante minutes dans chaque sens. Une soumission de hachage prenait quatre-vingts minutes pour produire une preuve. L'équipage s'adapta en regroupant les soumissions : une fois par semaine, Fatou collectait tous les nouveaux hachages, les soumettait en un seul lot, et récupérait les preuves au cycle suivant."
        "En cinquième année, le délai dépassait deux heures dans chaque sens. L'arriéré des hachages non ancrés — les combinateurs enregistrés depuis le dernier lot réussi — s'étirait parfois jusqu'à trois cents entrées. Les preuves arrivaient encore. Mais l'écart entre « ce combinateur existe » et « ce combinateur est prouvablement horodaté » avait grandi jusqu'à cinq heures les bons jours et douze heures quand l'antenne était réorientée pour une correction de trajectoire."
        "Lylia construisit une solution intermédiaire : une chaîne d'ancrage locale. Le navire maintenait sa propre chaîne de hachages, chaque bloc contenant un ensemble de hachages de combinateurs et un lien vers le bloc précédent. La chaîne n'était pas vérifiée par la Terre, mais elle était cohérente en interne. Quand les preuves terrestres arrivaient, le code de Lylia les insérait dans la chaîne au bloc approprié, ancrant rétroactivement les enregistrements locaux au temps externe."
        "L'arriéré ne se résorba jamais complètement. Ce n'était pas un échec. La preuve qu'un combinateur existait était dans le hachage. La preuve qu'il avait été créé avant un moment spécifique était dans la chaîne d'ancrage, même si ce moment était « avant le bloc N de notre chaîne locale, qui a été ancré au temps terrestre au bloc M ». C'était suffisant. C'était plus que la plupart des systèmes sur Terre ne pouvaient dire de leur propre histoire."))))
