(define post-23-le-chercheur-fr
  (lambda ()
    (list-of
      "23-le-chercheur"
      "Le Chercheur Indépendant"
      (list-of
        "Le professeur Sáenz était mort sur Terre huit mois avant le silence, de causes sans rapport avec quoi que ce soit que la mission aurait pu affecter. L'équipage l'apprit six semaines après le fait, dans l'un des derniers lots de messages avant le début du silence. Le message avait été envoyé par un ancien étudiant, qui pensait que l'équipage voudrait le savoir, et qui avait joint une brève notice nécrologique et une liste des derniers travaux publiés du professeur."
        "Parmi ces derniers travaux figurait un article, soumis trois semaines avant sa mort et publié à titre posthume, sur la fondation minimale des systèmes de programmation multilingues à adressage par contenu. L'article prouvait, formellement, que l'ensemble de primitives du dépôt de la mission était non seulement pratique mais théoriquement minimal compte tenu des contraintes de performance que l'équipe de la Cale avait spécifiées. C'était la formalisation de l'argument que lui et Yusuf avaient développé à la Cale, poussée plus loin que leurs sessions au tableau blanc ne l'avaient permis."
        "L'équipage enregistra l'article dans le dépôt comme document en langage naturel, avec une entrée d'attribution d'auteur pour le professeur Sáenz. Yusuf rédigea l'entrée du journal de travail, qui était plus longue que ses entrées de journal de travail habituelles. La phrase pertinente était : « Il a terminé la preuve que nous avions commencée. Il était sur Terre quand il l'a terminée ; nous étions en transit quand nous l'avons reçue. La distance entre nous au moment où ce document a été écrit était d'environ quarante minutes-lumière, et il contient des résultats sur un travail que nous avons fait dans la même pièce. »"
        "L'article devint une référence standard pour quiconque à bord travaillant avec la fondation du dépôt. Il était cité dans la documentation de lignée de cinq combinateurs ultérieurs. La citation incluait, dans le format utilisé par le dépôt pour l'attribution des auteurs : « Sáenz, E. (posthume). » La parenthèse n'était pas requise par le format du dépôt. Fatou l'avait ajoutée, et personne ne l'avait supprimée."
        "Amara traduisit le résumé de l'article dans les sept langues de surface enregistrées du dépôt. Elle enregistra chaque traduction comme dérivation de l'original en anglais, avec une relation 'translate' dans la lignée. La traduction en tamazight, pour laquelle elle avait demandé l'aide de Lylia, était celle dont le professeur aurait été le plus surpris. Il n'avait jamais travaillé dans un système capable d'accueillir le tamazight. Il avait écrit la théorie qui le rendait possible."))))
