(define post-25-la-chercheuse-fr
  (lambda ()
    (list-of
      "25-la-chercheuse"
      "La Chercheuse Académique"
      (list-of
        "Le programme de recherche du navire n'avait pas marqué de pause quand la Terre s'était tue. La science n'avait pas besoin de la permission de la Terre pour continuer. Ce dont elle avait besoin, c'était le dépôt, qui fonctionnait, les instruments, qui fonctionnaient, et l'équipage, dont la plupart fonctionnait bien, compte tenu de tout."
        "La Dr. Ines, l'astrophysicienne de la mission, avait un problème particulier en huitième année : elle avait besoin de publier. Non pas pour des raisons de carrière — sa carrière était, dans un sens significatif, en suspens jusqu'à ce que la Terre redevienne accessible. Elle avait besoin de publier parce qu'elle avait des résultats importants, que d'autres chercheurs devraient connaître, et qui seraient perdus s'ils n'existaient que dans ses notes personnelles."
        "Le dépôt était sa revue. Elle écrivit ses résultats sous forme de combinateurs structurés — des combinateurs de données dont le « corps » était un jeu de données précisément formaté, avec des liens de lignée vers les sessions d'observation qui avaient produit les données, et des documents en langage naturel qui décrivaient la méthodologie et l'interprétation. Elle enregistra sa clé d'auteur dans le système d'attribution, ajouta des horodatages via la chaîne d'ancrage locale, et écrivit un document intitulé « De la publication dans un dépôt plutôt que dans une revue »."
        "Le document arguait que la publication dans un dépôt était, aux fins de la mission, supérieure à la publication dans une revue : elle était persistante, versionnée, liée à sa propre histoire de dérivation, et immédiatement accessible à chaque membre de l'équipage sans les barrières d'accès qui avaient entravé la publication académique sur Terre. L'évaluation par les pairs était informelle — elle demanda à Rania et Pita de vérifier sa méthodologie, et leur vérification fut enregistrée comme combinateurs d'attestation dans le dépôt."
        "Quand le contact avec la Terre fut éventuellement rétabli — des années plus tard, après que l'antenne eut été reconstruite, après la fin du long silence — ses publications étaient déjà horodatées, évaluées par les pairs au sens du dépôt, et liées aux données brutes qui les avaient produites. Les revues qui reçurent ses soumissions ne surent que faire des formats de citation comportant des hachages SHA-256. Elle joignit un glossaire. Les évaluateurs trouvèrent cela inhabituel. Les résultats étaient corrects."))))
