(define post-28-l-invariant-fr
  (lambda ()
    (list-of
      "28-l-invariant"
      "L'Invariant"
      (list-of
        "Qu'est-ce qu'un système a besoin d'être vrai, toujours, quoi qu'il lui arrive ? C'est la question que Fatou posa à l'équipage lors de la réunion technique annuelle en neuvième année du voyage. Ils étaient dans le silence depuis deux ans. La réunion avait la qualité particulière des réunions tenues par des gens qui ont accepté que leur situation est permanente jusqu'à preuve du contraire."
        "Les réponses vinrent lentement, une à une, et Fatou les écrivit dans un combinateur document que tout le monde pouvait voir sur l'écran de la salle commune. La structure en ajout seul du dépôt : ce qui est ajouté ne peut être supprimé, seulement supplanté par dérivation. Le hachage comme identité : la chose est la même qu'elle était si et seulement si le hachage correspond. Le journal de travail comme continuité : rien n'est perdu qui a été validé, même si le processus qui l'a produit a disparu."
        "Rania en ajouta une qui surprit la salle : « Une vérification correcte qui passe aujourd'hui passera demain sur le même combinateur. » Personne ne l'avait énoncé explicitement auparavant. C'était une conséquence de l'immuabilité des hachages — un combinateur avec un hachage donné produirait toujours la même sortie pour la même entrée, donc une vérification testant une sortie spécifique pour une entrée spécifique donnerait toujours le même résultat sur ce combinateur. Ce n'était pas une propriété pour laquelle ils avaient conçu le système. C'était une conséquence de ce qu'ils avaient conçu."
        "La liste s'allongea jusqu'à neuf items. Fatou en ajouta un dixième : « Le dépôt est présent là où il est déployé. L'inaccessibilité de la Terre ne rend pas le dépôt moins présent. » Elle le lut à voix haute. La salle fut silencieuse un moment. Puis Chen dit : « C'est pour ça qu'on l'a appelé un invariant. » Quelqu'un d'autre dit : « C'est vraiment pour ça qu'on l'a appelé ainsi ? » Chen dit qu'il le pensait. Personne n'en était certain."
        "Le document fut intitulé « L'Invariant » et enregistré dans le dépôt. Ce fut le document le plus lu dans le dépôt du navire pour le reste du voyage. Chaque membre de l'équipage qui rejoignit le navire après la neuvième année le lut en premier, comme introduction, avant de lire quoi que ce soit d'autre. Il leur disait ce qui était vrai, toujours. C'était suffisant pour commencer."))))
