;; manifest-en: ordered list of English-language posts.
(define manifest-en
  (lambda ()
    (list-of
     (post-01-the-hold-en)
     (post-02-the-hacker-en)
     (post-03-the-polyglot-en)
     (post-04-the-senior-en)
     (post-05-the-kid-en)
     (post-06-the-theorist-en)
     (post-07-the-coordinator-en)
     (post-08-the-thinker-en)
     (post-09-the-air-cycle-en)
     (post-10-the-check-en)
     (post-11-departure-en)
     (post-12-the-privateer-en)
     (post-13-the-citizen-en)
     (post-14-the-educator-en)
     (post-15-the-connector-en)
     (post-16-the-symbiotic-en)
     (post-17-the-anchor-backlog-en)
     (post-18-the-refactor-en)
     (post-19-the-memory-wipe-en)
     (post-20-the-artist-en)
     (post-21-the-silence-en)
     (post-22-the-stolen-en)
     (post-23-the-researcher-en)
     (post-24-the-steward-en)
     (post-25-the-academic-en)
     (post-26-the-representative-en)
     (post-27-the-manifesto-en)
     (post-28-the-invariant-en)
     (post-29-the-language-en)
     (post-30-the-first-commit-en))))
