;; manifest-es: lista ordenada de los relatos en español.
(define manifest-es
  (lambda ()
    (list-of
     (post-01-la-bodega-es)
     (post-02-el-hacedor-es)
     (post-03-la-poliglota-es)
     (post-04-el-veterano-es)
     (post-05-la-chica-es)
     (post-06-el-teorico-es)
     (post-07-la-coordinadora-es)
     (post-08-el-pensador-es)
     (post-09-el-ciclo-aire-es)
     (post-10-la-verificacion-es)
     (post-11-la-partida-es)
     (post-12-el-corsario-es)
     (post-13-el-ciudadano-es)
     (post-14-la-educadora-es)
     (post-15-la-conectora-es)
     (post-16-la-ia-simbiotica-es)
     (post-17-el-rezago-ancla-es)
     (post-18-la-cascada-es)
     (post-19-el-borrado-es)
     (post-20-la-artista-es)
     (post-21-el-silencio-es)
     (post-22-la-despojada-es)
     (post-23-el-investigador-es)
     (post-24-la-gestora-es)
     (post-25-la-investigadora-es)
     (post-26-el-representante-es)
     (post-27-el-manifiesto-es)
     (post-28-el-invariante-es)
     (post-29-la-lengua-del-transito-es)
     (post-30-el-primer-commit-es))))
