(define post-08-el-pensador-es
  (lambda ()
    (list-of
      "08-el-pensador"
      "El Pensador Civilizacional"
      (list-of
        "El Dr. Osei no escribía código. Estaba en la Bodega porque alguien en el comité de planificación de la misión había leído su libro — una obra densa, admirada, raramente terminada, sobre lo que los sistemas de software revelan acerca de las civilizaciones que los producen — y había decidido que tener un historiador de la tecnología en el equipo valía el espacio en las literas. La mayoría de los ingenieros eran escépticos ante este razonamiento. Con el tiempo lo fueron menos."
        "Su contribución fue un memorando. Se titulaba 'Sobre la distinción entre memoria y registro' y tenía ocho páginas. El argumento central era este: la mayoría de los archivos digitales funcionaban como memoria — almacenaban lo ocurrido en un formato optimizado para la recuperación por personas que ya sabían lo que buscaban. El almacén, argumentaba, funcionaba como un registro — almacenaba lo ocurrido en un formato que preservaba el razonamiento, no solo el resultado, y que podía ser interrogado por personas que no habían estado presentes cuando se realizó el trabajo."
        "La distinción importaba para la misión. Si la tripulación necesitaba depurar un subsistema de soporte vital cinco años después de la partida, no podría preguntar a los ingenieros que lo habían construido. Los ingenieros estarían en la Tierra, inaccesibles, quizás jubilados, quizás muertos. Lo que tendrían era el almacén. El almacén les mostraría no solo lo que hacía el subsistema, sino la cadena de derivación que lo había producido, las verificaciones escritas contra él, los diarios de trabajo que explicaban por qué se habían tomado ciertas decisiones."
        "El memorando de Osei fue ampliamente leído y ampliamente debatido. Los ingenieros encontraban su estilo de prosa difícil. Él encontraba entrañable su tendencia a tratar todas las preguntas conceptuales como problemas de ingeniería. El memorando fue añadido al almacén como documento en lenguaje natural. Su hash apareció en el linaje de la especificación de diseño de la suite de verificaciones. Fatou lo había añadido allí, sin anunciarlo, como reconocimiento."
        "Dejó la Bodega después de seis semanas. En la ceremonia de despedida — pequeña, celebrada en la bahía de mantenimiento porque la sala común estaba en reparación — dijo que era optimista sobre la misión por una sola razón: las personas en el barco sabrían lo que no sabían, porque el almacén se lo diría. Pensaba que eso era más raro de lo que sonaba. Tenía razón."))))
