(define post-09-el-ciclo-aire-es
  (lambda ()
    (list-of
      "09-el-ciclo-aire"
      "El Ciclo de Aire"
      (list-of
        "El error estaba en la rutina de equilibrio de nitrógeno. Llevaba allí once meses, dormido, esperando una combinación específica de lecturas de sensores atmosféricos que solo ocurría cuando el ciclo mensual de purga profunda del sistema de reciclaje se ejecutaba al mismo tiempo que la prueba de ventilación del invernadero. Cuando esos dos eventos coincidían, la rutina de equilibrio de nitrógeno producía un valor dos órdenes de magnitud por debajo del correcto. La rutina entonces activaba una falsa alarma atmosférica."
        "Nadie encontró el error leyendo el código. El código había sido revisado dos veces y parecía correcto a ambos revisores. La fórmula de equilibrio de nitrógeno era correcta. La conversión de unidades era correcta. El caso límite — la interacción específica entre los dos ciclos concurrentes — no era una condición que nadie hubiera pensado en verificar, porque requería saber que ambos ciclos existían y que podían coincidir."
        "La suite de verificaciones lo encontró. Fatou había añadido una verificación para la rutina de equilibrio de nitrógeno que ejecutaba un conjunto tabular de entradas contra salidas esperadas. La tabla incluía varios valores del escenario de purga profunda, no porque alguien hubiera predicho el error, sino porque Fatou había pedido al equipo de sistemas ambientales una lista de combinaciones de entrada 'inusuales pero válidas', y las habían incluido sin saber por qué ella las quería."
        "Cuando la verificación falló durante una ejecución rutinaria de la suite, produjo una discordancia de hash en el valor de salida. Fatou lo llevó al equipo de sistemas ambientales. El equipo encontró el error en cuarenta minutos. La corrección fueron tres líneas. La rutina corregida fue confirmada como un nuevo hash, con un enlace de linaje al original y una entrada de diario de trabajo que describía en detalle el camino del descubrimiento."
        "La entrada terminaba: 'Encontrado por verificación, no por revisión. La verificación fue escrita antes de saber qué estaba verificando. Para eso sirven las verificaciones.' Esta frase fue citada más tarde en el segundo memorando del Dr. Osei, que escribió desde la Tierra después de recibir una copia del diario de trabajo. Lo llamó un ejemplo de estructura de conocimiento produciendo recuperación de conocimiento. La tripulación lo llamó buena suerte, que también era correcto."))))
