(define post-13-el-ciudadano-es
  (lambda ()
    (list-of
      "13-el-ciudadano"
      "El Ciudadano"
      (list-of
        "Tariq no era programador. Era médico, y su relación con los sistemas de software del barco era la misma que tiene la mayoría de las personas con los sistemas de los que depende: confiaba en ellos como se confía en un puente, cruzándolo y observando que aguantaba. Era un enfoque razonable. También era, cuanto más se alejaba el barco de la Tierra, un enfoque cada vez más incómodo."
        "El sistema de diagnóstico médico había sido construido a partir de una base de software de apoyo a la decisión clínica que Tariq había usado en la Tierra. Sabía cómo se sentía cuando funcionaba correctamente. Lo que no sabía — lo que nunca había necesitado saber en la Tierra, donde la línea de soporte del proveedor era una llamada telefónica — era por qué funcionaba correctamente. En el barco, el proveedor estaba a ocho minutos-luz y la distancia crecía. En el año dos, eran veinte minutos. En el año tres, obtener soporte útil de la Tierra requería noventa minutos de ida y vuelta para un solo intercambio de mensajes."
        "Fue a ver a Fatou. Dijo: 'Necesito entender lo suficiente del sistema de diagnóstico para poder mantenerlo.' Fatou dijo: 'Define mantener.' Él dijo: 'Necesito saber cuándo se equivoca y poder explicarle a alguien por qué.' Ella le mostró la suite de verificaciones. Le mostró cómo leer el linaje de un combinador. No le mostró cómo escribir un combinador, porque eso no era lo que había pedido."
        "Durante seis meses, Tariq aprendió a leer las verificaciones del sistema de diagnóstico como un médico cuidadoso lee un informe de laboratorio: no como datos en bruto, sino como un patrón de confirmaciones y excepciones. No podía escribir nuevas verificaciones. Podía leer las existentes y entender qué verificaban. Cuando fallaba una verificación, sabía qué categoría de corrección había sido violada, aunque no pudiera corregir la violación él mismo."
        "Escribió una guía para otros tripulantes no programadores llamada 'Leer el almacén sin escribirlo'. Tenía siete páginas. Fatou la añadió al almacén. Su hash apareció en el linaje de tres documentos posteriores escritos por tripulantes de otras disciplinas que habían aprendido la misma habilidad leyéndola. Tariq no consideraba esto como programación. Lo consideraba como alfabetización. No estaba equivocado."))))
