(define post-17-el-rezago-ancla-es
  (lambda ()
    (list-of
      "17-el-rezago-ancla"
      "El Rezago de Anclas"
      (list-of
        "El anclaje de marcas de tiempo abiertas funcionaba enviando un hash a un registro público mantenido en la Tierra y recibiendo una prueba de que el hash existía en un momento específico. La prueba era criptográfica: cualquiera que tuviera el registro podía verificar que el hash había sido enviado antes de cierto bloque, y por tanto que el contenido direccionado por el hash había existido antes de ese bloque."
        "Durante los dos primeros años del viaje, la tripulación enviaba hashes al registro terrestre y recibía pruebas en menos de una hora. El retardo de propagación de ida y vuelta era lo suficientemente pequeño para que el proceso fuera casi invisible. En el año tres, el retardo era de cuarenta minutos en cada sentido. Un envío de hash tardaba ochenta minutos en producir una prueba. La tripulación se adaptó agrupando los envíos: una vez a la semana, Fatou recopilaba todos los hashes nuevos, los enviaba en un único lote y recuperaba las pruebas en el siguiente ciclo."
        "En el año cinco, el retardo superaba las dos horas en cada sentido. El rezago de hashes sin anclar — combinadores registrados desde el último lote exitoso — a veces se extendía hasta trescientas entradas. Las pruebas seguían llegando. Pero la brecha entre 'este combinador existe' y 'este combinador tiene marca de tiempo demostrable' había crecido hasta cinco horas en un buen día y doce horas cuando la antena se reorientaba para una corrección de trayectoria."
        "Lylia construyó una solución provisional: una cadena de anclaje local. El barco mantenía su propia cadena de hashes, cada bloque conteniendo un conjunto de hashes de combinadores y un enlace al bloque anterior. La cadena no estaba verificada por la Tierra, pero era internamente consistente. Cuando llegaban las pruebas terrestres, el código de Lylia las insertaba en la cadena en el bloque apropiado, anclando retroactivamente los registros locales al tiempo externo."
        "El rezago nunca se resolvió del todo. Esto no era un fracaso. La prueba de que un combinador existía estaba en el hash. La prueba de que había sido creado antes de un momento específico estaba en la cadena de anclaje, incluso si ese momento era 'antes del bloque N de nuestra cadena local, que fue anclada al tiempo terrestre en el bloque M'. Era suficiente. Era más de lo que la mayoría de los sistemas en la Tierra podían decir sobre su propia historia."))))
