(define post-19-el-borrado-es
  (lambda ()
    (list-of
      "19-el-borrado"
      "El Borrado de Memoria"
      (list-of
        "El clúster de cómputo secundario perdió su memoria volátil durante un evento solar en el año seis. El evento no fue catastrófico — los sistemas primarios no se vieron afectados, la tripulación estaba ilesa, la trayectoria del barco no cambió. Pero el clúster secundario, que ejecutaba una simulación de larga duración del campo gravitacional del sistema de destino, perdió todo lo que no había sido confirmado en almacenamiento persistente. Cuarenta y siete horas de cómputo, perdidas."
        "O: cuarenta y siete horas de cómputo, parcialmente recuperables. Porque la simulación había estado ejecutándose dentro del entorno de evaluación del almacén, cada invocación de combinador que había completado antes del evento había sido registrada en el diario de trabajo. El estado final de la simulación había desaparecido. Su historia de derivación — cada paso que había llevado a ese estado — estaba en el almacén."
        "Emeka, que había asumido el trabajo de simulación después de que su autor original fuera reasignado a otro proyecto, pasó dos días leyendo el diario de trabajo. Reconstruyó el estado de la simulación en el último punto de control confirmado — once horas antes del evento — y volvió a ejecutar las últimas once horas. La nueva ejecución produjo los mismos resultados. Lo verificó comparando las salidas intermedias registradas en el diario de trabajo original con las salidas de la nueva ejecución. Coincidían."
        "El evento solar había destruido cuarenta y siete horas de tiempo de cómputo y cero horas de conocimiento. La distinción no era obvia para todos a bordo. Rania tuvo que explicarla en la reunión de la tripulación: el valor de la simulación no era el tiempo dedicado a calcularla, sino la relación entre las entradas y las salidas, que era el combinador. El combinador estaba en el almacén. El almacén había sobrevivido al evento porque el almacén era almacenamiento persistente, no memoria volátil."
        "Añadió una entrada de diario de trabajo a la simulación: 'Recuperado del evento solar mediante repetición del diario. 11 horas recalculadas. Resultados verificados contra registros previos al evento. El almacén aguantó.' Era la entrada más corta del diario de trabajo de la simulación. Emeka pensaba que era la más importante."))))
