(define post-21-el-silencio-es
  (lambda ()
    (list-of
      "21-el-silencio"
      "El Silencio"
      (list-of
        "El último mensaje de la Tierra llegó un martes, hora del barco, a las 14:32:07 UTC+8, el huso horario que la tripulación había elegido porque no pertenecía al huso horario de nadie y por tanto nadie tenía que adaptarse. El mensaje era un acuse de recibo de telemetría rutinaria. Decía, en el formato de datos compacto que la misión usaba para los intercambios de estado: todo nominal, próxima ventana en 72 horas. La ventana se abrió. Ningún mensaje la atravesó."
        "La antena funcionaba. El análisis era inequívoco: el transmisor del lado terrestre había enmudecido. No bloqueado — el perfil de ruido de fondo era limpio. No interferido — la geometría era correcta. Simplemente silencioso. La ventana de 72 horas pasó. Luego otra. La tripulación ejecutó la suite de diagnóstico en el sistema de antena. Todas las verificaciones pasaron. La antena estaba bien. La Tierra no transmitía."
        "No entraron en pánico. Esto merece énfasis: no entraron en pánico. Habían sido entrenados para escenarios de pérdida de comunicación, los habían discutido en ejercicios trimestrales y tenían un protocolo. El protocolo era continuar la misión según lo planificado, porque el plan de misión estaba en el almacén y el almacén no necesitaba la Tierra para funcionar. Lo que sentían era más difícil de nombrar — un cambio, como el momento en que te das cuenta de que llevas mucho tiempo conteniendo la respiración."
        "Tariq anotó en el diario de salud de la tripulación que la mayoría de los tripulantes dormían menos horas en la semana siguiente al silencio. No anotó qué informaban que hacían con las horas adicionales. La mayoría estaban en el almacén. Leyendo los diarios de trabajo. Siguiendo las cadenas de derivación hasta la Bodega, hasta el clúster Pi de Yusuf, hasta la Piedra de Rosetta anotada a mano que Yusuf había descrito en una entrada de diario de trabajo y que alguien había fotografiado y confirmado como combinador documento."
        "El almacén no cambió cuando la Tierra enmudeció. Cada hash que había estado en el almacén antes del silencio seguía estando en él después. Cada verificación seguía ejecutándose. Cada enlace de linaje seguía apuntando al mismo padre. El silencio era un evento externo. El almacén era interno. La tripulación lo sabía intelectualmente. Ahora lo estaba aprendiendo en un registro diferente."))))
