(define post-22-la-despojada-es
  (lambda ()
    (list-of
      "22-la-despojada"
      "La Despojada"
      (list-of
        "Rania había escrito la biblioteca de análisis espectral en el segundo año del viaje. La había escrito en un período de cuatro días intensivos, trabajando a través de dos ciclos de sueño, produciendo once combinadores que colectivamente permitían a los instrumentos del barco identificar la composición atmosférica a distancias donde los métodos anteriores requerían aproximaciones mucho más cercanas. Era, por cualquier medida, un trabajo importante."
        "Cuando buscó en el almacén dos años después, encontró su biblioteca citada en un trabajo derivado del que no sabía nada. El derivado estaba registrado por una clave de autor que no reconocía. La entrada del diario de trabajo del derivado decía solo: 'Extendido desde spectral-analysis-lib para entornos de alta albedo.' Sin reconocimiento. Sin comunicación. Sin registro de habérselo dicho."
        "Estaba enojada. Dejó reposar la rabia un día antes de hacer nada, porque la rabia era legítima y no quería manejarla mal. Luego leyó el derivado con detenimiento. Era técnicamente correcto. La extensión era útil. El autor no había cambiado su trabajo — había añadido sobre él, como el sistema de derivación estaba diseñado para permitir. El linaje del almacén dejaba claro que sus combinadores eran los ancestros de los suyos."
        "Solicitó una reunión de la tripulación. No para acusar a nadie — el autor no había hecho nada técnicamente incorrecto — sino para establecer una práctica. La práctica que propuso era simple: cuando derivas del trabajo de alguien, se lo dices. No porque el almacén lo requiera. El almacén no lo requiere; el almacén solo registra el enlace de derivación. Sino porque el trabajo venía de algún lugar, y la persona de la que venía estaba en el mismo barco."
        "La práctica fue adoptada. El autor, un tripulante más joven que genuinamente no había pensado en esta dimensión de la derivación, añadió un reconocimiento en el diario de trabajo. El linaje de la extensión incluía ahora una nota: 'Derivado de la biblioteca de análisis espectral de R. Khaled, con su conocimiento y agradecimiento.' Rania la leyó. No respondió. Volvió al trabajo. La biblioteca seguía siendo suya, en el único sentido que importaba: el hash apuntaba a lo que ella había construido."))))
