(define post-25-la-investigadora-es
  (lambda ()
    (list-of
      "25-la-investigadora"
      "La Investigadora Académica"
      (list-of
        "El programa de investigación del barco no había hecho pausa cuando la Tierra enmudeció. La ciencia no necesitaba el permiso de la Tierra para continuar. Lo que necesitaba era el almacén, que funcionaba, los instrumentos, que funcionaban, y la tripulación, la mayoría de la cual funcionaba bien, considerando todo."
        "La Dra. Ines, la astrofísica de la misión, tenía un problema particular en el año ocho: necesitaba publicar. No por razones de carrera — su carrera estaba, en un sentido significativo, en suspenso hasta que la Tierra volviera a ser accesible. Necesitaba publicar porque tenía resultados que eran importantes, que otros investigadores deberían conocer, y que se perderían si solo existían en sus notas personales."
        "El almacén era su revista. Escribió sus resultados como combinadores estructurados — combinadores de datos cuyo 'cuerpo' era un conjunto de datos precisamente formateado, con enlaces de linaje a las sesiones de observación que habían producido los datos, y documentos en lenguaje natural que describían la metodología e interpretación. Registró su clave de autor en el sistema de atribución, añadió marcas de tiempo a través de la cadena de anclaje local, y escribió un documento titulado 'Sobre publicar en un almacén en lugar de en una revista'."
        "El documento argumentaba que la publicación en un almacén era, a los efectos de la misión, superior a la publicación en revistas: era persistente, estaba versionada, estaba vinculada a su propia historia de derivación, y estaba inmediatamente disponible para cada tripulante sin las barreras de acceso que habían plagado la publicación académica en la Tierra. La revisión por pares era informal — pidió a Rania y Pita que verificaran su metodología, y su verificación fue registrada como combinadores de atestación en el almacén."
        "Cuando el contacto con la Tierra se restableció eventualmente — años después, tras reconstruir la antena, tras el final del largo silencio — sus publicaciones ya tenían marcas de tiempo, habían sido revisadas por pares en el sentido del almacén, y estaban vinculadas a los datos en bruto que las habían producido. Las revistas que recibieron sus envíos no sabían qué hacer con formatos de cita que incluían hashes SHA-256. Adjuntó un glosario. Los revisores lo encontraron inusual. Los resultados eran correctos."))))
