(define post-26-el-representante-es
  (lambda ()
    (list-of
      "26-el-representante"
      "El Representante"
      (list-of
        "La cuestión de gobernanza había estado latente desde la partida. La misión había sido lanzada bajo un marco diseñado para una tripulación que recibiría orientación de la Tierra — actualizaciones del protocolo de misión, decisiones de asignación de recursos, arbitraje de disputas que la tripulación no pudiera resolver internamente. Cuando la Tierra enmudeció, el marco tenía un vacío en su centro donde había estado la autoridad."
        "La tripulación no llenó el vacío inmediatamente. Durante el primer año del silencio, operaron con el marco anterior al silencio por inercia, tomando pequeñas decisiones localmente y aplazando las más grandes. Las grandes decisiones se acumularon. En el segundo año del silencio, la lista de aplazamientos era lo suficientemente larga como para que Fatou convocara una asamblea de la tripulación para abordarla."
        "La asamblea decidió, después de dos días de discusión, que el almacén funcionaría como memoria institucional de la misión para las decisiones de gobernanza, de la misma manera que funcionaba como memoria institucional para las decisiones técnicas. Una decisión de gobernanza sería propuesta como documento en lenguaje natural, discutida a través de entradas de diario de trabajo adjuntas a ese documento, y ratificada por atestación — un número umbral de tripulantes firmando el documento con sus claves de autor."
        "La primera persona en proponer un documento de gobernanza fue un ingeniero de estructuras llamado Gabriel, que representaba, informalmente, una facción de la tripulación preocupada por la asignación de recursos para el programa de investigación creciente versus la carga de trabajo de mantenimiento. Su propuesta era cuidadosa, específica y bien fundamentada en los documentos de protocolo de misión existentes en el almacén. La discusión que generó produjo dieciocho entradas de diario de trabajo en cinco días."
        "El documento ratificado fue registrado en el almacén con todos los hashes de atestación. No era vinculante en el sentido legal que los documentos del lado terrestre eran vinculantes. Era vinculante de la manera en que todo en el almacén era vinculante: existía, tenía marca de tiempo, estaba firmado, y podía ser leído por cualquiera. Las decisiones futuras lo citaron como precedente, de la misma manera que los combinadores técnicos citaban sus combinadores ancestros. El almacén no era una ley. Pero era un registro de lo que la tripulación había acordado, en el orden en que lo había acordado, y eso resultó ser suficiente."))))
