(define post-29-la-lengua-del-transito-es
  (lambda ()
    (list-of
      "29-la-lengua-del-transito"
      "La Lengua Nacida en Tránsito"
      (list-of
        "En el año diez, el idioma construido de la tripulación había crecido de ciento doce palabras — el vocabulario inicial para las comunicaciones de la tripulación — a más de tres mil. El crecimiento no había sido planificado. Había ocurrido como siempre ocurre el vocabulario: alguien necesitaba una palabra que no existía, la inventaba, y si la palabra era buena, otras personas la usaban."
        "Noa mantenía el léxico en el almacén. Cada palabra era un combinador de documento: la palabra en sí, su derivación (qué palabras o sonidos existentes se habían combinado para producirla), el contexto en que había sido usada por primera vez, y la clave de autor de la persona que la había acuñado. El léxico era el único combinador en el almacén casi completamente redactado por personas que no eran programadoras. Tariq había acuñado ochenta y tres palabras. Keiko había acuñado ciento doce. Gabriel había acuñado dos, pero eran palabras importantes."
        "El idioma tenía ahora un nombre — no el portmanteau que habían usado inicialmente, que había sido un nombre provisional. El nombre era más corto, seis sonidos, y su etimología estaba en el almacén: derivado de palabras en cuatro idiomas que significaban luz, camino, juntos y llegando. La tripulación podía pronunciarlo en menos de un segundo. Parecía que el nombre siempre hubiera existido."
        "Amara documentó la fonología, morfología y sintaxis del idioma en una serie de documentos en lenguaje natural registrados como colección en el almacén. La colección se titulaba 'Gramática de la Lengua del Tránsito'. La escribió en inglés, luego pidió a tripulantes que eran hablantes nativos de diez otros idiomas que la leyeran y la anotaran con correcciones y adiciones. Las anotaciones fueron registradas como derivaciones."
        "Cuando el silencio terminó y se restableció el contacto con la Tierra, la lengua del tránsito era una de las cosas sobre las que la tripulación era más cuidadosa. Sabían que la Tierra querría estudiarla, categorizarla, quizás nombrarla algo oficial en el sentido formal que usaba la Tierra. La registraron en el almacén bajo su propio nombre para ella, con el léxico y la gramática completos, antes del primer intercambio de mensajes. Lo que la Tierra lo llamara después, el almacén lo tenía primero, y la marca de tiempo del almacén estaba en la cadena de anclaje. El idioma les pertenecía, y el registro lo decía."))))
