;; manifest-fr: liste ordonnée des récits en français.
(define manifest-fr
  (lambda ()
    (list-of
     (post-01-la-cale-fr)
     (post-02-le-bricoleur-fr)
     (post-03-la-polyglotte-fr)
     (post-04-le-veteran-fr)
     (post-05-la-gamine-fr)
     (post-06-le-theoricien-fr)
     (post-07-la-coordinatrice-fr)
     (post-08-le-penseur-fr)
     (post-09-le-cycle-air-fr)
     (post-10-la-verification-fr)
     (post-11-le-depart-fr)
     (post-12-le-corsaire-fr)
     (post-13-la-citoyenne-fr)
     (post-14-l-educatrice-fr)
     (post-15-la-relieuse-fr)
     (post-16-l-ia-symbiotique-fr)
     (post-17-l-arriere-ancre-fr)
     (post-18-la-cascade-fr)
     (post-19-l-effacement-fr)
     (post-20-l-artiste-fr)
     (post-21-le-silence-fr)
     (post-22-celle-qu-on-a-volee-fr)
     (post-23-le-chercheur-fr)
     (post-24-la-gardienne-fr)
     (post-25-la-chercheuse-fr)
     (post-26-le-representant-fr)
     (post-27-le-manifeste-fr)
     (post-28-l-invariant-fr)
     (post-29-la-langue-du-transit-fr)
     (post-30-le-premier-commit-fr))))
