(define post-08-the-thinker-en
  (lambda ()
    (list-of
      "08-the-thinker"
      "The Civilizational Thinker"
      (list-of
        "Dr. Osei did not write code. He was in the Hold because someone on the mission planning committee had read his book — a dense, admired, rarely-finished work about what software systems reveal about the civilizations that produce them — and decided that having a historian of technology on the team was worth the bunk space. Most of the engineers were skeptical of this reasoning. They became less skeptical over time."
        "His contribution was a memo. It was titled 'On the Distinction Between Memory and Record' and it was eight pages long. The core argument was that most digital archives functioned as memory — they stored what had happened in a format optimized for retrieval by people who already knew what they were looking for. The store, he argued, functioned as a record — it stored what had happened in a format that preserved the reasoning, not just the result, and that could be interrogated by people who had not been present when the work was done."
        "The distinction mattered for the mission. If the crew needed to debug a life-support subsystem five years into the voyage, they could not ask the engineers who had built it. The engineers would be on Earth, unreachable, possibly retired, possibly dead. What they had was the store. The store would show them not just what the subsystem did, but the derivation chain that had produced it, the checks that had been written against it, the worklogs that explained why certain decisions had been made."
        "Osei's memo was widely read and widely argued with. The engineers found his prose style difficult. He found their tendency to treat all conceptual questions as engineering problems endearing. The memo was added to the store as a natural-language document. Its hash appeared in the lineage of the check suite's design specification. Fatou had added it there, without announcement, as an acknowledgment."
        "He left the Hold after six weeks. At the departure ceremony — a small one, held in the maintenance bay because the common room was being repaired — he said he was optimistic about the mission for one reason only: the people on the ship would know what they did not know, because the store would tell them. He thought that was rarer than it sounded. He was right."))))
