(define post-23-the-researcher-en
  (lambda ()
    (list-of
      "23-the-researcher"
      "The Independent Researcher"
      (list-of
        "Professor Sáenz had died on Earth eight months before the silence, of causes unrelated to anything the mission could have affected. The crew learned of it six weeks after the fact, in one of the last message batches before the silence began. The message had been sent by a former student, who thought the crew would want to know, and who attached a brief obituary and a list of the professor's final published works."
        "Among the final works was a paper, submitted three weeks before his death and published posthumously, on the minimal foundation for content-addressed multilingual programming systems. The paper proved, formally, that the primitive set in the mission's store was not merely practical but theoretically minimal for the performance constraints the Hold's team had specified. It was the formalization of the argument he and Yusuf had worked through in the Hold, carried further than their whiteboard sessions had gone."
        "The crew registered the paper in the store as a natural-language document, with an author attribution entry for Professor Sáenz. Yusuf wrote the worklog entry, which was longer than his worklog entries usually were. The relevant sentence was: 'He finished the proof we started. He was on Earth when he finished it; we were in transit when we received it. The distance between us when this document was written was approximately forty light-minutes, and it contains results about work we did in the same room.'"
        "The paper became a standard reference for anyone on the ship working with the store's foundation. It was cited in five subsequent combiners' lineage documentation. The citation included, in the format the store used for author attribution: 'Sáenz, E. (posthumous).' The parenthetical was not required by the store's format. Fatou had added it, and no one had removed it."
        "Amara translated the paper's abstract into all seven of the store's registered surface languages. She registered each translation as a derivation from the English original, with a `translate` relation in the lineage. The Tamazight translation, which she had asked Lylia to help with, was the one the professor would have been most surprised by. He had never worked in a system that could accommodate Tamazight. He had written the theory that made it possible."))))
