(define post-02-le-bricoleur-fr
  (lambda ()
    (list-of
      "02-le-bricoleur"
      "Le Bricoleur du Garage"
      (list-of
        "Yusuf arriva à la Cale avec un sac marin, un fer à souder et la conviction que tout problème soluble en théorie était soluble avant le petit-déjeuner. Il n'était pas officiellement membre de l'équipe d'ingénierie. On l'avait invité parce qu'il avait déjà construit un dépôt à adressage par contenu en un week-end, pour des raisons que personne ne comprenait vraiment, et que ça marchait."
        "Son espace de travail occupait un coin de la baie de maintenance où l'odeur de l'huile de machine ne disparaissait jamais tout à fait. Il relia un câble du réseau de capteurs structuraux à un cluster de Raspberry Pi assemblé à partir de pièces de rechange, et appela l'ensemble son banc d'essai. L'équipe des systèmes officiels de la Cale le regardait avec la méfiance particulière que l'on réserve aux gens qui produisent des résultats sans ouvrir de tickets."
        "Le premier problème que Yusuf résolut fut l'amorçage. Un dépôt à adressage par contenu a besoin d'un moyen d'enregistrer ses propres primitives — mais ces primitives ne sont pas encore dans le dépôt au moment du démarrage. Il écrivit la table des primitives sur papier d'abord, puis la retranscrivit dans un fichier que l'évaluateur pouvait charger avant de consulter le dépôt. Le papier existait encore, collé au mur au-dessus de son cluster. L'équipe l'appela la Pierre de Rosette."
        "Il ne nommait pas ses combinateurs avec soin au début. Il les appelait des choses comme 'q', 'qq', 'qqq'. Quand Amara, la Programmeuse Polyglotte, le découvrit, il s'ensuivit un désaccord bref et animé. La position de Yusuf était que les noms n'étaient que présentation, pas logique, et que le hachage était ce qui comptait. La position d'Amara était qu'un système que personne ne pouvait lire était un système que personne ne pourrait jamais faire confiance. Ils avaient tous les deux raison. Le système de nommage qu'ils conçurent ensemble fut celui qui fut livré."
        "Au dix-huitième jour de la première rotation, l'alimentation du cluster tomba en panne. Trois heures de travail étaient en mémoire volatile. Yusuf les récupéra depuis le journal des hachages, car chaque évaluation avait été validée. Il n'en dit rien à personne. Il continua simplement à travailler."))))
