(define post-07-la-coordinatrice-fr
  (lambda ()
    (list-of
      "07-la-coordinatrice"
      "La Coordinatrice"
      (list-of
        "Personne n'avait engagé Fatou spécifiquement pour coordonner le travail d'intégration logicielle de la Cale. Le rôle avait existé comme un vide dans l'organigramme pendant les trois premiers mois, ce qui voulait dire que Fatou — qui avait une formation en ingénierie des systèmes et un don pour voir les choses se désintégrer avant qu'elles ne le fassent — l'avait comblé en se présentant à chaque réunion et en notant ce que les gens convenaient de faire."
        "Sa première contribution systématique fut la suite de vérifications. Le dépôt disposait d'un mécanisme pour associer des procédures de vérification aux combinateurs — de petits programmes testant des invariants et rapportant succès ou échec — mais personne n'avait écrit de vérifications pour la bibliothèque de base. Fatou passa deux semaines à lire chaque combinateur de la bibliothèque de base, à écrire une vérification pour chacun, puis à exécuter la suite complète chaque matin avant la réunion d'équipe. Elle ouvrait des tickets pour tout ce qui échouait."
        "Les vérifications n'étaient pas des mathématiques nouvelles. C'était le genre de chose qu'un programmeur attentif vérifierait à la main : est-ce que la liste vide se comporte correctement, est-ce que la concaténation de chaînes préserve la longueur, est-ce que la fonction d'échappement gère les cas limites. Ce qui les rendait précieuses, c'est qu'elles s'exécutaient. Chaque jour. Contre le dépôt réel, pas une simulation."
        "Quand un combinateur était modifié — par Yusuf, par Lylia, par n'importe qui — les vérifications s'exécutaient à nouveau. L'immuabilité du dépôt signifiait que modifier un combinateur produisait un nouveau hachage, et le nouveau hachage portait un nouvel ensemble de vérifications. Fatou suivait quelles vérifications avaient été écrites pour quelles versions. Quand une version était remplacée, les vérifications restaient attachées à son hachage. On pouvait toujours vérifier que l'ancienne version se comportait encore comme elle s'était comportée autrefois."
        "Elle forma trois autres membres de l'équipage à écrire des vérifications avant le départ. Elle rédigea un guide intitulé « À quoi sert une vérification », qui faisait quatre paragraphes et ne contenait pas de code. Le guide fut ajouté au dépôt sous un hachage. C'était le premier document en langage naturel enregistré dans le système, et il survécut au voyage."))))
