(define post-10-la-verification-fr
  (lambda ()
    (list-of
      "10-la-verification"
      "La Vérification"
      (list-of
        "Trois semaines avant la fenêtre de départ, la Cale effectua son test d'intégration final. Pas un test logiciel — un test d'environnement complet. Chaque système qui voyagerait sur le navire fut mis en route simultanément pendant soixante-douze heures aux niveaux de charge que le profil de mission prévoyait pour la première année de phase de croisière. La tâche de l'équipe logicielle était de surveiller le dépôt."
        "Ils le surveillaient comme on surveille quelqu'un en qui on a confiance mais qu'on ne peut pas voir entièrement : en cherchant des changements de comportement plutôt que des preuves de défaillance. Chaque combinateur appelé enregistrait son appel dans le journal de travail. Chaque vérification exécutée enregistrait son résultat. Au bout de soixante-douze heures, l'équipe disposait d'un enregistrement complet de ce que le système avait fait, dans l'ordre dans lequel il l'avait fait, traçable jusqu'à la version exacte de chaque combinateur impliqué."
        "Deux anomalies apparurent. L'une était un problème de synchronisation dans la couche de routage réseau, trouvé dans les journaux et corrigé avant la fin du test. L'autre était plus étrange : un combinateur qui avait été remplacé six mois plus tôt était encore appelé par un sous-système qui n'avait pas été mis à jour pour utiliser la nouvelle version. Les deux versions étaient correctes. Les deux étaient dans le dépôt. Le sous-système utilisait l'ancienne parce que personne ne lui avait dit qu'il existait une nouvelle."
        "La correction ne consistait pas à supprimer l'ancien combinateur — c'était impossible ; le dépôt était en ajout seulement. La correction consistait à ajouter un lien de dérivation de l'ancien hachage vers le nouveau, à marquer l'ancien hachage comme supplanté, et à mettre à jour le manifeste du sous-système. Le sous-système résolvait alors le nom vers la nouvelle version au chargement. L'ancienne version demeurait, documentée, accessible, son journal de travail intact."
        "Le dernier jour avant le verrouillage de la fenêtre de départ, Yusuf exécuta la suite de vérifications complète une dernière fois. Toutes les vérifications passèrent. Il ajouta une entrée dans le journal de travail : « Prêt. » Fatou ajouta la sienne : « Prêt. » Lylia, qui avait veillé toute la nuit à exécuter l'intégration des capteurs environnementaux, ajouta : « Prêt, je pense. » Le dépôt les enregistra toutes les trois. Le navire était prêt. Savoir si l'équipage l'était aussi, c'était une question d'une autre nature."))))
