(define post-13-la-citoyenne-fr
  (lambda ()
    (list-of
      "13-la-citoyenne"
      "La Citoyenne"
      (list-of
        "Tariq n'était pas programmeur. Il était médecin, et sa relation aux systèmes logiciels du navire était la même que celle de la plupart des gens avec les systèmes dont ils dépendent : il leur faisait confiance comme on fait confiance à un pont, en le traversant et en observant qu'il tenait. C'était une approche raisonnable. C'était aussi, plus le navire s'éloignait de la Terre, une approche de plus en plus inconfortable."
        "Le système de diagnostic médical avait été construit à partir d'un socle de logiciels d'aide à la décision clinique que Tariq avait utilisés sur Terre. Il savait ce qu'on ressentait quand ils fonctionnaient correctement. Ce qu'il ne savait pas — ce qu'il n'avait jamais eu besoin de savoir sur Terre, où la ligne d'assistance du fournisseur était un coup de téléphone — c'était pourquoi ils fonctionnaient correctement. Sur le navire, le fournisseur se trouvait à huit minutes-lumière et la distance grandissait. En deuxième année, c'était vingt minutes. En troisième année, obtenir une assistance utile de la Terre nécessitait quatre-vingt-dix minutes aller-retour pour un seul échange de message."
        "Il alla voir Fatou. Il dit : « J'ai besoin de comprendre suffisamment le système de diagnostic pour pouvoir l'entretenir. » Fatou dit : « Définissez entretenir. » Il dit : « J'ai besoin de savoir quand il se trompe et de pouvoir expliquer pourquoi à quelqu'un. » Elle lui montra la suite de vérifications. Elle lui montra comment lire la lignée d'un combinateur. Elle ne lui montra pas comment écrire un combinateur, parce que ce n'est pas ce qu'il avait demandé."
        "En six mois, Tariq apprit à lire les vérifications du système de diagnostic comme un médecin attentif lit un rapport de laboratoire : non pas comme des données brutes, mais comme un schéma de confirmations et d'exceptions. Il ne pouvait pas écrire de nouvelles vérifications. Il pouvait lire les existantes et comprendre ce qu'elles vérifiaient. Quand une vérification échouait, il savait quelle catégorie de correction avait été violée, même s'il ne pouvait pas réparer la violation lui-même."
        "Il rédigea un guide pour les autres membres d'équipage non-programmeurs intitulé « Lire le dépôt sans l'écrire ». Il faisait sept pages. Fatou l'ajouta au dépôt. Son hachage apparut dans la lignée de trois documents ultérieurs écrits par des membres d'équipage d'autres disciplines qui avaient appris la même compétence en le lisant. Tariq ne considérait pas cela comme de la programmation. Il considérait cela comme de l'alphabétisation. Il n'avait pas tort."))))
