(define post-14-l-educatrice-fr
  (lambda ()
    (list-of
      "14-l-educatrice"
      "L'Éducatrice"
      (list-of
        "Chen enseignait la programmation depuis quinze ans avant la mission. Il avait enseigné dans des universités, dans des formations intensives, dans une plateforme en ligne qui touchait un demi-million d'étudiants et dont le pourcentage qu'il percevait lui semblait embarrassant à calculer. Il avait appris, au fil des années, que la chose la plus difficile à enseigner n'était ni la syntaxe ni les algorithmes, mais le moment où un apprenant a une pensée que ses outils peuvent exprimer."
        "Sur le navire, il enseignait un étudiant à la fois, car le complément d'équipage ne permettait pas de travailler en cohortes. Son premier étudiant après le départ était une ingénieure en matériaux nommée Pita, qui voulait écrire des combinateurs pour l'analyse des contraintes. Pita avait une formation en modélisation par éléments finis et un sens intuitif solide de la structure mathématique. Ce qu'elle n'avait pas, c'était une façon de penser la logique nommée, hachée et multilingue — le modèle spécifique qu'utilisait le dépôt."
        "Chen ne commença pas par le dépôt. Il commença par les mathématiques que Pita connaissait déjà. Il lui montra qu'une clause gamma était un filtrage de motifs sur un type de données inductif, ce qu'elle comprenait dans le contexte des structures de maillage. Elle dit : « Donc le gamma est la règle de récursion, et le cas de base est le motif qui ne récurse pas. » Il dit que c'était exactement ça. Elle écrivit son premier gamma correctement vingt minutes plus tard."
        "La leçon qu'il ajouta au dépôt était la leçon elle-même — non pas la transcription, mais la structure pédagogique : la séquence des concepts, l'exemple qui avait créé la connexion, la formulation qui avait fonctionné. Il l'écrivit comme un document en langage naturel et l'enregistra comme dérivation d'un document de pédagogie générale que Marcus avait écrit à la Cale, lui-même dérivé du guide de Tariq."
        "Un an plus tard, un membre de l'équipage qu'il n'avait pas enseigné — une spécialiste en hydroponie nommée Emeka, qui avait lu le document de leçon dans le dépôt — vint le trouver pour lui dire qu'elle s'était auto-formée grâce à lui. Elle lui montra les combinateurs qu'elle avait écrits. Ils étaient corrects. Il bifurqua le document de leçon pour ajouter une note : « Confirmé auto-enseignable. 2e instance. » Il en était très content."))))
