(define post-19-l-effacement-fr
  (lambda ()
    (list-of
      "19-l-effacement"
      "L'Effacement de Mémoire"
      (list-of
        "Le cluster de calcul secondaire perdit sa mémoire volatile lors d'un événement solaire en sixième année. L'événement n'était pas catastrophique — les systèmes primaires étaient inaffectés, l'équipage était sain, la trajectoire du navire était inchangée. Mais le cluster secondaire, qui exécutait une simulation de longue durée du champ gravitationnel du système de destination, perdit tout ce qui n'avait pas été validé en stockage persistant. Quarante-sept heures de calcul, perdues."
        "Ou : quarante-sept heures de calcul, partiellement récupérables. Parce que la simulation s'était déroulée dans l'environnement d'évaluation du dépôt, chaque invocation de combinateur terminée avant l'événement avait été enregistrée dans le journal de travail. L'état final de la simulation avait disparu. Son histoire de dérivation — chaque étape qui avait mené à cet état — était dans le dépôt."
        "Emeka, qui avait repris le travail de simulation après que son auteur original eut été affecté à un autre projet, passa deux jours à lire le journal de travail. Elle reconstitua l'état de la simulation au dernier point de contrôle validé — onze heures avant l'événement — et exécuta à nouveau les onze dernières heures. La nouvelle exécution produisit les mêmes résultats. Elle le vérifia en comparant les sorties intermédiaires enregistrées dans le journal de travail original avec les sorties de la nouvelle exécution. Elles correspondaient."
        "L'événement solaire avait détruit quarante-sept heures de temps de calcul et zéro heure de connaissance. La distinction n'était pas évidente pour tout le monde à bord. Rania dut l'expliquer lors de la réunion de l'équipage : la valeur de la simulation n'était pas le temps passé à la calculer, mais la relation entre les entrées et les sorties, qui était le combinateur. Le combinateur était dans le dépôt. Le dépôt avait survécu à l'événement parce que le dépôt était un stockage persistant, et non une mémoire volatile."
        "Elle ajouta une entrée de journal de travail à la simulation : « Récupéré après événement solaire via relecture du journal. 11 heures recalculées. Résultats vérifiés par rapport aux journaux pré-événement. Le dépôt a tenu. » C'était l'entrée la plus courte du journal de travail de la simulation. Emeka pensait que c'était la plus importante."))))
