(define post-20-l-artiste-fr
  (lambda ()
    (list-of
      "20-l-artiste"
      "L'Artiste"
      (list-of
        "Le rôle officiel de Keiko était illustratrice de systèmes, un poste qui n'avait pas existé avant la mission et que l'équipage avait inventé parce que quelqu'un devait produire des diagrammes techniques et que les ingénieurs s'accordaient tous à dire que leurs propres diagrammes étaient, selon les mots de Yusuf, « honnêtes mais pénibles ». Elle arriva avec une formation en visualisation de données et une pratique privée dans l'art génératif qui n'avait rien à voir avec les voyages spatiaux."
        "Elle passa ses six premiers mois sur le navire à produire les diagrammes que tout le monde lui demandait : graphes de dépendances, cartes d'architecture système, visualisations de lignée pour les chaînes de combinateurs du dépôt. Elle était douée pour cela de la façon spécifique dont les gens sont doués pour des choses qui mobilisent une partie de leur attention en laissant le reste disponible pour d'autres problèmes."
        "L'autre problème sur lequel elle travaillait était la question de ce à quoi un combinateur ressemblait en tant qu'image. Pas un diagramme — pas une illustration de ses relations — mais un encodage visuel direct de son contenu. Elle passa trois mois à développer une correspondance : la structure d'arbre de Bruijn devenait un chemin ramifié ; la profondeur de chaque branche encodait la complexité récursive du combinateur ; les nœuds feuilles étaient colorés selon leur signature de type. Les images résultantes n'étaient pas belles au sens conventionnel. Elles étaient distinctives. Deux combinateurs à structure similaire mais non identique produisaient des images similaires mais non identiques. Deux combinateurs avec le même hachage produisaient la même image."
        "Elle les appela « portraits de hachage ». L'équipage commença à les utiliser comme sommes de contrôle visuelles — un coup d'œil rapide à un portrait permettait de confirmer qu'un combinateur n'avait pas changé. Ce n'était pas rigoureux. La vérification réelle était le hachage. Mais les portraits étaient utiles de la façon dont les mnémotechniques sont utiles : non pas comme substitut à l'exactitude, mais comme aide-mémoire."
        "Elle ajouta un générateur de portraits de hachage dans le dépôt comme combinateur. Son propre portrait — l'image du combinateur qui générait des images — était l'un des plus complexes que le système pouvait produire, dense et ramifié. Elle l'imprima et l'accrocha près de son poste de travail. Quand les nouveaux membres de l'équipage demandaient ce que c'était, elle disait : « C'est une image de lui-même en train de faire des images. » Ils trouvaient cela déroutant. Elle pensait que c'était approprié."))))
