(define post-21-le-silence-fr
  (lambda ()
    (list-of
      "21-le-silence"
      "Le Silence"
      (list-of
        "Le dernier message de la Terre arriva un mardi, heure du navire, à 14h32min07s UTC+8, le fuseau horaire que l'équipage avait choisi parce qu'il n'appartenait à personne et ne nécessitait donc l'adaptation de personne. Le message était un accusé de réception de télémétrie de routine. Il disait, dans le format de données compact utilisé pour les échanges de statut : tout nominal, prochaine fenêtre dans 72 heures. La fenêtre s'ouvrit. Aucun message ne la traversa."
        "L'antenne fonctionnait. L'analyse était sans ambiguïté : l'émetteur côté Terre s'était tu. Pas brouillé — le profil de bruit de fond était propre. Pas bloqué — la géométrie était correcte. Simplement silencieux. La fenêtre de 72 heures passa. Puis une autre. L'équipage exécuta la suite de diagnostics sur le système d'antenne. Toutes les vérifications passèrent. L'antenne allait bien. La Terre n'émettait plus."
        "Ils ne paniquèrent pas. Cela mérite d'être souligné : ils ne paniquèrent pas. Ils avaient été formés aux scénarios de perte de communication, ils les avaient discutés lors d'exercices trimestriels, et ils disposaient d'un protocole. Le protocole consistait à poursuivre la mission telle que planifiée, parce que le plan de mission était dans le dépôt et que le dépôt n'avait pas besoin de la Terre pour fonctionner. Ce qu'ils ressentaient était plus difficile à nommer — un changement, comme au moment où l'on réalise qu'on retient son souffle depuis longtemps."
        "Tariq nota dans le journal de santé de l'équipage que la plupart des membres dormaient moins d'heures dans la semaine suivant le silence. Il ne nota pas ce qu'ils rapportaient faire des heures supplémentaires. La plupart d'entre eux se trouvaient dans le dépôt. Lisant les journaux de travail. Suivant les chaînes de dérivation jusqu'à la Cale, jusqu'au cluster Pi de Yusuf, jusqu'à la Pierre de Rosette annotée à la main que Yusuf avait décrite dans une entrée de journal de travail et que quelqu'un avait photographiée et enregistrée comme combinateur document."
        "Le dépôt ne changea pas quand la Terre se tut. Chaque hachage qui était dans le dépôt avant le silence s'y trouvait encore après. Chaque vérification s'exécutait encore. Chaque lien de lignée pointait encore vers le même parent. Le silence était un événement externe. Le dépôt était interne. L'équipage le savait intellectuellement. Ils l'apprenaient maintenant dans un registre différent."))))
