(define post-22-celle-qu-on-a-volee-fr
  (lambda ()
    (list-of
      "22-celle-qu-on-a-volee"
      "Celle à Qui l'on a Volé"
      (list-of
        "Rania avait écrit la bibliothèque d'analyse spectrale en deuxième année du voyage. Elle l'avait écrite en une période de quatre jours intensifs, travaillant à travers deux cycles de sommeil, produisant onze combinateurs qui permettaient collectivement aux instruments du navire d'identifier la composition atmosphérique à des distances où les méthodes précédentes nécessitaient une approche beaucoup plus proche. C'était, par tout critère, un travail important."
        "Quand elle chercha dans le dépôt deux ans plus tard, elle trouva sa bibliothèque citée dans un travail dérivé dont elle ignorait l'existence. Le dérivé était enregistré par une clé d'auteur qu'elle ne reconnaissait pas. L'entrée de journal de travail du dérivé disait seulement : « Étendu à partir de spectral-analysis-lib pour les environnements à haute albédo. » Aucun remerciement. Aucune communication. Aucune trace d'en avoir informé la principale intéressée."
        "Elle était en colère. Elle laissa reposer la colère une journée avant de faire quoi que ce soit, parce que la colère était légitime et qu'elle ne voulait pas la gérer mal. Puis elle lut attentivement le dérivé. Il était techniquement correct. L'extension était utile. L'auteur n'avait pas modifié son travail — il y avait ajouté quelque chose, comme le système de dérivation était conçu pour le permettre. La lignée du dépôt indiquait clairement que ses combinateurs étaient les ancêtres des leurs."
        "Elle demanda une réunion de l'équipage. Non pas pour accuser quiconque — l'auteur n'avait rien fait de techniquement incorrect — mais pour établir une pratique. La pratique qu'elle proposait était simple : quand on dérive du travail de quelqu'un, on l'en informe. Non pas parce que le dépôt l'exige. Le dépôt ne l'exige pas ; le dépôt enregistre seulement le lien de dérivation. Mais parce que le travail venait de quelque part, et que la personne dont il venait se trouvait sur le même navire."
        "La pratique fut adoptée. L'auteur, un membre plus jeune de l'équipage qui n'avait sincèrement pas pensé à cette dimension de la dérivation, ajouta un remerciement dans le journal de travail. La lignée de l'extension comprenait désormais une note : « Dérivé de la bibliothèque d'analyse spectrale de R. Khaled, avec sa connaissance et ses remerciements. » Rania la lut. Elle ne répondit pas. Elle retourna travailler. La bibliothèque était encore la sienne, dans le seul sens qui comptait : le hachage pointait vers ce qu'elle avait construit."))))
