(define post-24-la-gardienne-fr
  (lambda ()
    (list-of
      "24-la-gardienne"
      "La Gardienne de la Communauté"
      (list-of
        "Noa était la gestionnaire de communauté de facto du dépôt depuis trois ans quand le silence tomba. Ce n'était pas un rôle qui avait été conçu dans la mission ; il avait grandi autour du fait que Noa était la personne qui remarquait quand les gens avaient des difficultés avec le dépôt et les aidait sans qu'on le lui demande. Elle avait un don pour identifier le moment où quelqu'un était sur le point d'abandonner l'enregistrement d'un combinateur parce que les outils semblaient trop peu familiers, et pour apparaître à ce moment-là avec une offre tranquille d'aide."
        "Après le silence, elle proposa quelque chose à quoi elle pensait depuis un an : ajouter une nouvelle langue de surface au dépôt. Non pas une langue parlée par un membre actuel de l'équipage. Une langue qui avait été construite, collectivement, sur le navire — une lingua franca qui avait émergé du mélange particulier des dix-huit origines linguistiques à bord et qui servait de medium neutre pour les communications de l'équipage quand la langue maternelle de personne n'était dominante."
        "La langue n'avait pas de nom. C'était la première chose que Noa demanda à l'équipage de décider. Le processus de nommage prit trois semaines et produisit, par consensus, un nom qui était un mot-valise de mots provenant de sept des dix-huit langues représentées, signifiant approximativement « le chemin que nous traçons ensemble ». Le nom était imprononçable pour la plupart des linguistes sur Terre. Il était utilisé couramment par chaque membre de l'équipage en moins d'un mois."
        "Elle enregistra les dix premiers combinateurs dans la nouvelle langue. C'étaient les combinateurs de la bibliothèque de base : les opérations fondamentales que tout programmeur à bord aurait besoin de connaître. Elle travailla avec Amara sur la phonologie et avec Lylia sur le processus formel d'enregistrement des noms. Le dépôt accepta la nouvelle langue sans modification — il avait toujours été conçu pour accueillir des correspondances de surface arbitraires. Le premier combinateur enregistré dans la langue de l'équipage résolut au même hachage que son équivalent anglais."
        "La langue n'avait pas de locuteurs sur Terre. Le dépôt s'en moquait. Le hachage était le même hachage qu'il avait toujours été. Le nom était nouveau. C'était tout le propos : le nom leur appartenait, fait par eux, pour leur usage, dans la seule communauté qui savait comment le prononcer."))))
