(define post-26-le-representant-fr
  (lambda ()
    (list-of
      "26-le-representant"
      "Le Représentant"
      (list-of
        "La question de gouvernance était latente depuis le départ. La mission avait été lancée dans un cadre conçu pour un équipage qui recevrait des orientations de la Terre — des mises à jour du protocole de mission, des décisions d'allocation des ressources, l'arbitrage des différends que l'équipage ne pouvait pas résoudre en interne. Quand la Terre se tut, le cadre avait un vide en son centre où l'autorité avait été."
        "L'équipage ne combla pas le vide immédiatement. Pendant la première année du silence, ils fonctionnèrent selon le cadre d'avant le silence par inertie, prenant de petites décisions localement et différant les plus grandes. Les grandes décisions s'accumulèrent. En deuxième année du silence, la liste des décisions différées était suffisamment longue pour que Fatou convoque une assemblée de l'équipage pour y remédier."
        "L'assemblée décida, après deux jours de discussion, que le dépôt fonctionnerait comme mémoire institutionnelle de la mission pour les décisions de gouvernance, de la même façon qu'il fonctionnait comme mémoire institutionnelle pour les décisions techniques. Une décision de gouvernance serait proposée comme document en langage naturel, discutée via des entrées de journal de travail attachées à ce document, et ratifiée par attestation — un nombre seuil de membres de l'équipage signant le document avec leurs clés d'auteur."
        "La première personne à proposer un document de gouvernance était un ingénieur de structure nommé Gabriel, qui représentait, informellement, une faction de l'équipage préoccupée par l'allocation des ressources pour le programme de recherche croissant par rapport à la charge de travail de maintenance. Sa proposition était soignée, spécifique, bien étayée par les documents de protocole de mission existants dans le dépôt. La discussion qu'elle généra produisit dix-huit entrées de journal de travail en cinq jours."
        "Le document ratifié fut enregistré dans le dépôt avec tous les hachages d'attestation. Il n'était pas contraignant au sens juridique où les documents côté Terre l'étaient. Il était contraignant de la façon dont tout dans le dépôt était contraignant : il existait, il était horodaté, il était signé, et pouvait être lu par n'importe qui. Les décisions futures le citèrent comme précédent, de la même façon que les combinateurs techniques citaient leurs combinateurs ancêtres. Le dépôt n'était pas une loi. Mais c'était un registre de ce que l'équipage avait convenu, dans l'ordre où il l'avait convenu, et cela s'avéra suffisant."))))
