(define post-27-le-manifeste-fr
  (lambda ()
    (list-of
      "27-le-manifeste"
      "Le Manifeste"
      (list-of
        "Le deuxième livre du Dr. Osei arriva dans le dernier lot de messages avant le silence : un dense PDF de 340 pages, envoyé par son éditeur à sa demande avec la note « au cas où vous auriez le temps de le lire là-bas ». L'équipage eut le temps. Le livre fut lu, par sections, par presque tout le monde à bord, et la discussion qu'il généra dura des mois dans les canaux publics de l'équipage, eux-mêmes stockés comme combinateurs de document dans le dépôt."
        "Le chapitre qui généra le plus de discussion était intitulé « Contre l'architecture accidentelle ». Son argument était le suivant : chaque système logiciel durable accumulait ce qu'Osei appelait une architecture accidentelle — une structure qui n'avait pas été conçue mais avait grandi autour des contingences de l'histoire du développement. L'architecture accidentelle n'était pas nécessairement mauvaise ; elle capturait parfois une connaissance de domaine réelle qui n'avait jamais été rendue explicite. Mais elle était fragile, parce que personne ne comprenait pourquoi elle existait, et coûteuse à modifier, parce que la modifier nécessitait de reconstruire le raisonnement qui l'avait produite."
        "Le dépôt, argumentait Osei, était une tentative de rendre toute architecture explicite — non pas en empêchant la croissance accidentelle, mais en enregistrant la chaîne de dérivation ayant produit chaque structure. Un membre d'équipage lisant le graphe de lignée du dépôt pouvait, en principe, remonter n'importe quel combinateur jusqu'à la décision originale qui l'avait rendu nécessaire. L'architecture n'était pas accidentelle ; elle était une contingence documentée."
        "Yusuf écrivit une réponse dans le canal public. Elle était brève : « C'est à ça que servait la suite de vérifications de Fatou. La vérification est l'énoncé explicite de l'intention. Le hachage est la preuve que le code correspond à l'intention. Le journal de travail est l'histoire de la façon dont on y est arrivé. » Il ajouta : « J'aurais dû écrire ceci à la Cale. Je ne savais pas comment le formuler à l'époque. »"
        "La réponse fut ajoutée au dépôt comme entrée de journal de travail sur un combinateur document pointant vers le chapitre et la note de Yusuf. Le nom du combinateur document, dans la langue de transit de l'équipage, se traduisait par « la conversation entre le livre et le travail ». Personne sur Terre ne pouvait lire ce nom. L'équipage le pouvait. Ils l'avaient fait."))))
