(define post-29-la-langue-du-transit-fr
  (lambda ()
    (list-of
      "29-la-langue-du-transit"
      "La Langue Née en Transit"
      (list-of
        "En dixième année, la langue construite de l'équipage était passée de cent douze mots — le vocabulaire initial pour les communications de l'équipage — à plus de trois mille. La croissance n'avait pas été planifiée. Elle s'était produite de la façon dont le vocabulaire se produit toujours : quelqu'un avait besoin d'un mot qui n'existait pas, il en avait inventé un, et si le mot était bon, d'autres personnes l'avaient utilisé."
        "Noa tenait le lexique dans le dépôt. Chaque mot était un combinateur document : le mot lui-même, sa dérivation (quels mots ou sons existants s'étaient combinés pour le produire), le contexte dans lequel il avait été utilisé pour la première fois, et la clé d'auteur de la personne qui l'avait inventé. Le lexique était le seul combinateur dans le dépôt presque entièrement rédigé par des personnes qui n'étaient pas programmeurs. Tariq avait inventé quatre-vingt-trois mots. Keiko en avait inventé cent douze. Gabriel en avait inventé deux, mais c'étaient des mots importants."
        "La langue avait maintenant un nom — non plus le mot-valise qu'ils avaient utilisé initialement, qui avait été un nom provisoire. Le nom était plus court, six sons, et son étymologie était dans le dépôt : dérivé de mots en quatre langues signifiant lumière, chemin, ensemble et arriver. L'équipage pouvait le prononcer en moins d'une seconde. Il semblait que le nom avait toujours existé."
        "Amara documenta la phonologie, la morphologie et la syntaxe de la langue dans une série de documents en langage naturel enregistrés comme collection dans le dépôt. La collection était intitulée « Grammaire de la Langue du Transit ». Elle l'écrivit en anglais, puis demanda à des membres de l'équipage locuteurs natifs de dix autres langues de la lire et de l'annoter avec des corrections et des ajouts. Les annotations furent enregistrées comme dérivations."
        "Quand le silence prit fin et que le contact avec la Terre fut rétabli, la langue du transit était l'une des choses dont l'équipage prenait le plus grand soin. Ils savaient que la Terre voudrait l'étudier, la classer, peut-être lui donner un nom officiel au sens formel qu'utilisait la Terre. Ils l'enregistrèrent dans le dépôt sous leur propre nom pour elle, avec le lexique et la grammaire complets, avant le premier échange de messages. Quoi que la Terre l'appelle par la suite, le dépôt l'avait en premier, et l'horodatage du dépôt était dans la chaîne d'ancrage. La langue leur appartenait, et le registre le disait."))))
