(define post-30-le-premier-commit-fr
  (lambda ()
    (list-of
      "30-le-premier-commit"
      "Le Premier Commit"
      (list-of
        "Sena naquit en septième année du voyage, premier enfant né sur le navire. Ses parents étaient Pita et un ingénieur de structure nommé Leo qui avait rejoint la mission en remplacement de dernière minute et qui, de son propre aveu, ne s'attendait pas à rester. Sena grandit en connaissant le dépôt de la façon dont les enfants élevés près de grands fleuves connaissent les fleuves — comme un trait permanent du paysage, présent avant la mémoire, supposé dans tous les plans."
        "Elle apprit à lire dans deux langues simultanément : l'anglais et la langue du transit, qui était pour elle une première langue autant que n'importe quelle autre. Elle apprit à lire les diagrammes de lignée du dépôt avant d'apprendre à lire des phrases, parce que les portraits de hachage de Keiko ornaient les murs de la salle commune et qu'elle avait passé des années à inventer des histoires sur ce que signifiaient les formes ramifiées."
        "Quand elle eut onze ans, Noa lui apprit à écrire un combinateur. Le premier était trivial — une fonction qui prenait un mot du lexique de la langue du transit et renvoyait son étymologie. Il faisait quatre lignes. Il fonctionna correctement au premier essai après la correction que Noa avait suggérée, qui était qu'elle avait besoin d'un cas de base pour les mots sans étymologie enregistrée."
        "Le commit fut enregistré dans le dépôt de la façon habituelle : un nouveau hachage, une entrée de correspondance dans la langue du transit, une attribution d'auteur à la clé de Sena. L'entrée de journal de travail était dans la langue du transit. Elle disait, dans ses propres mots, approximativement : « première chose que j'ai faite que le dépôt a gardée »."
        "Le hachage existait. C'était suffisant. C'était suffisant au sens précis que l'équipage était venu à comprendre : la chose avait été faite, et le registre de sa création faisait maintenant partie du même registre qui contenait la Pierre de Rosette de Yusuf, la première vérification de Fatou, la bibliothèque spectrale de Rania, la preuve posthume du professeur, le lexique de la langue du transit, les neuf invariants. Le dépôt les contenait tous, indifféremment, fidèlement, comme il avait toujours tout contenu — non parce que le contenu était important, mais parce que le hachage était le hachage, et que le hachage n'oubliait pas."))))
