(define post-10-la-verificacion-es
  (lambda ()
    (list-of
      "10-la-verificacion"
      "La Verificación"
      (list-of
        "Tres semanas antes de la ventana de partida, la Bodega realizó su prueba de integración final. No una prueba de software — una prueba de entorno completa. Cada sistema que viajaría en el barco fue ejecutado simultáneamente durante setenta y dos horas a los niveles de carga que el perfil de misión preveía para el primer año de la fase de crucero. El trabajo del equipo de software era vigilar el almacén."
        "Lo vigilaban como se vigila a una persona de confianza que no se puede ver del todo: buscando cambios en el comportamiento más que evidencias de fallo. Cada combinador que era llamado registraba su llamada en el diario de trabajo. Cada verificación que se ejecutaba registraba su resultado. Al cabo de setenta y dos horas, el equipo tenía un registro completo de lo que había hecho el sistema, en el orden en que lo había hecho, rastreable hasta la versión exacta de cada combinador involucrado."
        "Surgieron dos anomalías. Una era un problema de temporización en la capa de enrutamiento de red, encontrado en los registros y corregido antes de que terminara la prueba. La otra era más extraña: un combinador que había sido reemplazado seis meses antes seguía siendo llamado por un subsistema que no había sido actualizado para usar la nueva versión. Ambas versiones eran correctas. Ambas estaban en el almacén. El subsistema usaba la antigua porque nadie le había dicho que existía una nueva."
        "La corrección no consistía en eliminar el combinador antiguo — eso no era posible; el almacén era de solo adición. Consistía en añadir un enlace de derivación del hash antiguo al nuevo, marcar el hash antiguo como superado y actualizar el manifiesto del subsistema. El subsistema entonces resolvía el nombre hacia la nueva versión en tiempo de carga. La versión antigua permanecía, documentada, recuperable, su diario de trabajo intacto."
        "El último día antes de que se bloqueara la ventana de partida, Yusuf ejecutó la suite completa de verificaciones una última vez. Todas las verificaciones pasaron. Añadió una entrada en el diario de trabajo: 'Listo.' Fatou añadió la suya: 'Listo.' Lylia, que había permanecido despierta toda la noche ejecutando la integración de sensores ambientales, añadió: 'Listo, creo.' El almacén las registró todas. El barco estaba listo. Si la tripulación lo estaba era una pregunta de otra naturaleza."))))
