(define post-14-la-educadora-es
  (lambda ()
    (list-of
      "14-la-educadora"
      "La Educadora"
      (list-of
        "Chen llevaba quince años enseñando programación antes de la misión. Había enseñado en universidades, en bootcamps, en una plataforma en línea que llegaba a medio millón de estudiantes y que le pagaba un porcentaje que le resultaba embarazoso calcular. Había aprendido, a lo largo de esos años, que lo más difícil de enseñar no era la sintaxis ni los algoritmos, sino el momento en que un aprendiz tiene un pensamiento que sus herramientas pueden expresar."
        "En el barco, enseñaba a un estudiante a la vez, porque el complemento de tripulación no permitía cohortes. Su primera estudiante después de la partida fue una ingeniera de materiales llamada Pita, que quería escribir combinadores para análisis de tensiones. Pita tenía formación en modelado de elementos finitos y un fuerte sentido intuitivo de la estructura matemática. Lo que no tenía era una forma de pensar en la lógica nombrada, hasheada y multilingüe — el modelo específico que usaba el almacén."
        "Chen no empezó por el almacén. Empezó por las matemáticas que Pita ya conocía. Le mostró que una cláusula gamma era una coincidencia de patrones sobre un tipo de dato inductivo, algo que ella entendía en el contexto de las estructuras de malla. Ella dijo: 'Entonces el gamma es la regla de recursión, y el caso base es el patrón que no recursa.' Él dijo que era exactamente correcto. Ella escribió su primer gamma correctamente veinte minutos después."
        "La lección que añadió al almacén era la lección en sí misma — no la transcripción, sino la estructura pedagógica: la secuencia de conceptos, el ejemplo que había creado la conexión, la frase que había funcionado. La escribió como documento en lenguaje natural y la registró como derivación de un documento de pedagogía general que Marcus había escrito en la Bodega, que a su vez se había derivado de la guía de Tariq."
        "Un año después, un tripulante al que no había enseñado — una especialista en hidroponía llamada Emeka, que había leído el documento de lección en el almacén — vino a decirle que se había autoformado con él. Le mostró los combinadores que había escrito. Eran correctos. Bifurcó el documento de lección para añadir una nota: 'Confirmado autoenseñable. 2ª instancia.' Estaba muy satisfecho con esto."))))
