(define post-15-la-conectora-es
  (lambda ()
    (list-of
      "15-la-conectora"
      "La Conectora"
      (list-of
        "El descubrimiento ocurrió por accidente, como muchos descubrimientos importantes. Amara buscaba en el almacén un combinador de procesamiento de cadenas que había escrito dos años antes, antes de la partida, y encontró que la búsqueda devolvía dos resultados para lo que ella creía que era un concepto único. Abrió ambos. Eran combinadores diferentes, escritos por personas diferentes, con nombres diferentes, en idiomas diferentes. Bajo la normalización de Bruijn, eran el mismo árbol. El mismo hash."
        "Las dos personas eran Pita — que había escrito un formateador de cadenas para análisis de tensiones — y Emeka, la especialista en hidroponía que se había autoformado con el documento de lección de Chen. Pita había llamado al suyo 'segment-format' en inglés. Emeka había llamado al suyo 'segmentu-fa' en yoruba, un idioma que usaba cuando quería pensar con claridad sin que su vocabulario inglés interfiriera. Habían llegado a una lógica idéntica desde puntos de partida diferentes, en idiomas diferentes, sin saber que la otra existía."
        "Amara las reunió. La reunión fue, según el testimonio posterior de la tripulación, los cuarenta y cinco minutos más productivos de los primeros tres años del viaje. Pita explicó el contexto del análisis de tensiones. Emeka explicó el contexto del modelado del crecimiento de plantas. Descubrieron que ambos contextos necesitaban la misma operación subyacente: dividir una secuencia estructurada en segmentos de tamaño fijo y aplicar una transformación a cada segmento. La estructura abstracta era la misma; el dominio de aplicación era diferente."
        "El combinador ya existía en el almacén con el nombre de Pita y el nombre de Emeka. Amara añadió una referencia cruzada en el diario de trabajo, vinculando ambas correspondencias a una única nota de documentación que explicaba la abstracción en inglés, yoruba y una notación que había desarrollado para este tipo preciso de descubrimiento interdisciplinar. Llamó a la nota un 'registro de convergencia'."
        "Empezó a llevar una lista de todos los registros de convergencia en el almacén. En un año, la lista tenía once entradas. La presentó en la reunión técnica anual de la tripulación. El punto que argumentaba era simple: el almacén no solo registraba lo que la gente había construido. Registraba lo que la gente había descubierto independientemente. El barco estaba haciendo ciencia sobre su propio conocimiento."))))
