(define post-20-la-artista-es
  (lambda ()
    (list-of
      "20-la-artista"
      "La Artista"
      (list-of
        "El papel oficial de Keiko era ilustradora de sistemas, un puesto que no había existido antes de la misión y que la tripulación había inventado porque alguien tenía que producir diagramas técnicos y todos los ingenieros coincidían en que sus propios diagramas eran, en palabras de Yusuf, 'honestos pero perturbadores'. Llegó con experiencia en visualización de datos y una práctica privada de arte generativo que no tenía nada que ver con los viajes espaciales."
        "Pasó sus primeros seis meses en el barco produciendo los diagramas que todo el mundo le pedía: grafos de dependencias, mapas de arquitectura de sistemas, visualizaciones de linaje para las cadenas de combinadores del almacén. Era buena en esto de la manera específica en que las personas son buenas en cosas que ocupan una parte de su atención mientras dejan el resto disponible para otros problemas."
        "El otro problema en el que trabajaba era la pregunta de cómo era un combinador como imagen. No un diagrama — no una ilustración de sus relaciones — sino una codificación visual directa de su contenido. Pasó tres meses desarrollando una correspondencia: la estructura de árbol de Bruijn se convertía en un camino ramificado; la profundidad de cada rama codificaba la complejidad recursiva del combinador; los nodos hoja estaban coloreados según su firma de tipo. Las imágenes resultantes no eran bellas en ningún sentido convencional. Eran distintivas. Dos combinadores con estructura similar pero no idéntica producían imágenes similares pero no idénticas. Dos combinadores con el mismo hash producían la misma imagen."
        "Los llamó 'retratos de hash'. La tripulación empezó a usarlos como sumas de comprobación visuales — un vistazo rápido a un retrato podía confirmar que un combinador no había cambiado. No era riguroso. La verificación real era el hash. Pero los retratos eran útiles de la manera en que los mnemónicos son útiles: no como sustituto de la corrección sino como ayuda para la memoria."
        "Añadió un generador de retratos de hash al almacén como combinador. Su propio retrato — la imagen del combinador que generaba imágenes — era uno de los más complejos que el sistema podía producir, denso y ramificado. Lo imprimió y lo colgó junto a su puesto de trabajo. Cuando los nuevos tripulantes preguntaban qué era, ella decía: 'Es una imagen de sí mismo haciendo imágenes.' Lo encontraban desconcertante. Ella pensaba que era apropiado."))))
