(define post-23-el-investigador-es
  (lambda ()
    (list-of
      "23-el-investigador"
      "El Investigador Independiente"
      (list-of
        "El profesor Sáenz había muerto en la Tierra ocho meses antes del silencio, por causas sin relación con nada que la misión pudiera haber afectado. La tripulación se enteró seis semanas después del hecho, en uno de los últimos lotes de mensajes antes de que comenzara el silencio. El mensaje lo había enviado un antiguo estudiante, que pensó que la tripulación querría saberlo, y que adjuntó una breve necrológica y una lista de los últimos trabajos publicados del profesor."
        "Entre esos últimos trabajos había un artículo, enviado tres semanas antes de su muerte y publicado póstumamente, sobre la base mínima para sistemas de programación multilingüe con direccionamiento por contenido. El artículo demostraba, formalmente, que el conjunto de primitivas en el almacén de la misión no era solo práctico sino teóricamente mínimo dado las restricciones de rendimiento que el equipo de la Bodega había especificado. Era la formalización del argumento que él y Yusuf habían elaborado en la Bodega, llevado más lejos de lo que sus sesiones en la pizarra habían podido llegar."
        "La tripulación registró el artículo en el almacén como documento en lenguaje natural, con una entrada de atribución de autor para el profesor Sáenz. Yusuf escribió la entrada del diario de trabajo, que era más larga de lo habitual en él. La frase relevante era: 'Terminó la prueba que empezamos. Estaba en la Tierra cuando la terminó; estábamos en tránsito cuando la recibimos. La distancia entre nosotros cuando se escribió este documento era de aproximadamente cuarenta minutos-luz, y contiene resultados sobre un trabajo que hicimos en la misma habitación.'"
        "El artículo se convirtió en una referencia estándar para cualquiera a bordo que trabajara con la base del almacén. Era citado en la documentación de linaje de cinco combinadores posteriores. La cita incluía, en el formato que el almacén usaba para la atribución de autores: 'Sáenz, E. (póstumo).' El paréntesis no era requerido por el formato del almacén. Fatou lo había añadido, y nadie lo había eliminado."
        "Amara tradujo el resumen del artículo a los siete idiomas de superficie registrados del almacén. Registró cada traducción como derivación del original en inglés, con una relación 'translate' en el linaje. La traducción al tamazight, para la que había pedido ayuda a Lylia, era la que más habría sorprendido al profesor. Nunca había trabajado en un sistema que pudiera acomodar el tamazight. Había escrito la teoría que lo hacía posible."))))
