(define post-24-la-gestora-es
  (lambda ()
    (list-of
      "24-la-gestora"
      "La Gestora de la Comunidad"
      (list-of
        "Noa había sido la gestora de comunidad de facto del almacén durante tres años cuando cayó el silencio. No era un papel que hubiera sido diseñado en la misión; había crecido alrededor del hecho de que Noa era la persona que notaba cuando la gente tenía dificultades con el almacén y les ayudaba sin que se lo pidieran. Tenía un don para identificar el momento en que alguien estaba a punto de rendirse en el registro de un combinador porque las herramientas parecían poco familiares, y aparecer en ese momento con un ofrecimiento tranquilo de ayuda."
        "Después del silencio, propuso algo en lo que había estado pensando durante un año: añadir un nuevo idioma de superficie al almacén. No un idioma hablado por ningún tripulante actual. Un idioma que había sido construido, colectivamente, en el barco — una lingua franca que había emergido de la mezcla particular de dieciocho orígenes lingüísticos a bordo y que servía como medio neutral para las comunicaciones de la tripulación cuando la lengua materna de nadie era dominante."
        "El idioma no tenía nombre. Eso era lo primero que Noa pidió a la tripulación que decidiera. El proceso de nombramiento tomó tres semanas y produjo, por consenso, un nombre que era un portmanteau de palabras de siete de los dieciocho idiomas representados, significando aproximadamente 'el camino que estamos trazando juntos'. El nombre era impronunciable para la mayoría de los lingüistas en la Tierra. Era usado fluidamente por cada tripulante en menos de un mes."
        "Registró los primeros diez combinadores en el nuevo idioma. Estos eran la biblioteca base: las operaciones fundamentales que cualquier programador a bordo necesitaría conocer. Trabajó con Amara en la fonología y con Lylia en el proceso formal de registro de nombres. El almacén aceptó el nuevo idioma sin modificación — siempre había sido diseñado para acomodar correspondencias de superficie arbitrarias. El primer combinador registrado en el idioma de la tripulación se resolvió al mismo hash que su equivalente en inglés."
        "El idioma no tenía hablantes en la Tierra. Al almacén no le importaba. El hash era el mismo hash que siempre había sido. El nombre era nuevo. Ese era el punto: el nombre les pertenecía, hecho por ellos, para su uso, en la única comunidad que sabía cómo pronunciarlo."))))
