(define post-27-el-manifiesto-es
  (lambda ()
    (list-of
      "27-el-manifiesto"
      "El Manifiesto"
      (list-of
        "El segundo libro del Dr. Osei llegó en el último lote de mensajes antes del silencio: un denso PDF de 340 páginas, enviado por su editor a petición suya con la nota 'por si tenéis tiempo de leerlo allí fuera'. La tripulación tuvo tiempo. El libro fue leído, por secciones, por casi todos a bordo, y la discusión que generó duró meses en los canales públicos de la tripulación, que a su vez estaban almacenados como combinadores de documento en el almacén."
        "El capítulo que generó más discusión se titulaba 'Contra la arquitectura accidental'. Su argumento era este: cada sistema de software de larga duración acumulaba lo que Osei llamaba arquitectura accidental — estructura que no había sido diseñada sino que había crecido alrededor de las contingencias de la historia del desarrollo. La arquitectura accidental no era necesariamente mala; a veces capturaba conocimiento de dominio genuino que nunca había sido explicitado. Pero era frágil, porque nadie entendía por qué existía, y cara de modificar, porque modificarla requería reconstruir el razonamiento que la había producido."
        "El almacén, argumentaba Osei, era un intento de hacer toda arquitectura explícita — no impidiendo el crecimiento accidental, sino registrando la cadena de derivación que producía cada estructura. Un tripulante leyendo el grafo de linaje del almacén podía, en principio, rastrear cualquier combinador hasta la decisión original que lo había hecho necesario. La arquitectura no era accidental; era contingencia documentada."
        "Yusuf escribió una respuesta en el canal público. Era breve: 'Para eso era la suite de verificaciones de Fatou. La verificación es la declaración explícita de intención. El hash es la prueba de que el código coincide con la intención. El diario de trabajo es la historia de cómo llegamos allí.' Añadió: 'Debería haber escrito esto en la Bodega. Entonces no sabía cómo decirlo.'"
        "La respuesta fue añadida al almacén como entrada de diario de trabajo en un combinador de documento que apuntaba tanto al capítulo como a la nota de Yusuf. El nombre del combinador de documento, en el idioma de tránsito de la tripulación, se traducía como 'la conversación entre el libro y el trabajo'. Nadie en la Tierra podía leer ese nombre. La tripulación podía. Lo habían hecho."))))
